import type { MiddleChapter } from "./types";

export const MIDDLE_CHAPTERS: MiddleChapter[] = [
  {
    id: "numbers", number: 1, title: "数与式",
    description: "从有理数到实数，掌握数轴、绝对值、整式运算等代数基础。",
    prerequisites: ["正整数和零的加减乘除"],
    teachingPoints: ["数轴是连接数字和几何的桥梁", "绝对值是距离概念的数学校验", "乘法公式是因式分解的基础"],
    commonMisconceptions: ["混淆相反数和绝对值", "使用平方差公式时忘记检查两项形式", "二次根式化简不彻底"],
    discussionQuestions: ["为什么 a\u00B2 \u2265 0 对所有实数 a 都成立？", "请举一个生活中用到绝对值的例子。"],
    knowledgePoints: [
      {
        id: "num-real-numberline", chapterId: "numbers", title: "有理数、实数与数轴",
        objectives: ["会区分有理数和无理数", "能在数轴上准确表示有理数", "会比较两个数的大小"],
        motivation: "天气预报说今天-3\u00B0C，海拔1000米，银行账户余额-50元。这些数字有正有负，只用正整数不够用了。",
        intuition: "把数轴想象成一条无限长的马路的数标。原点0是起点，右边越远越大（正数），左边越远越小（负数）。每个数在这条路上都有唯一的位置。",
        definition: "有理数是可以表示为两个整数之比的数（q/p，p\u22600）。无理数是不能写成两个整数之比的数（如\u03C0，\u221A2）。全体有理数和无理数构成实数集。数轴是一条直线，每一个实数对应数轴上的唯一点。",
        formulaLatex: "\\mathbb{R} = \\mathbb{Q} \\cup \\{\\text{无理数}\\}",
        formulaExplanation: "R表示实数集，Q表示有理数集。数轴上的每个点对应一个实数，反之亦然。",
        conditions: "所有实数都可以在数轴上表示。有理数和无理数的区别在于能否用分数形式表达。",
        example: {
          problem: "比较 -2.5 和 -3 的大小，并在数轴上标出它们的位置。",
          steps: [
            { description: "在数轴上，越往右数越大", latex: "-3 < -2.5" },
            { description: "两个负数的比较：绝对值越小越大", latex: "|-3| = 3 > |-2.5| = 2.5" },
            { description: "所以-2.5 在-3 的右边", latex: "\\therefore -2.5 > -3" },
          ],
          answer: "-2.5 > -3",
          answerLatex: "-2.5 > -3",
        },
        commonMistakes: [
          { mistake: "认为 -2.5 < -3（受正数思维影响）", correction: "两个负数比较时，绝对值大的反而小。" },
          { mistake: "认为所有小数都是有理数", correction: "无限不循环小数（如\u03C0=3.14159..）是无理数。" },
        ],
        summary: ["数轴：原点、正方向、单位长度三要素", "有理数与无理数组成实数", "数轴上右边的数总比左边的数大"],
        selfCheck: ["\u03C0 是有理数吗？为什么？", "在数轴上标出 -1, 0, 0.5, 2, -3.5。比较它们的大小。"],
      },
      {
        id: "num-absolute-value", chapterId: "numbers", title: "绝对值及其几何意义",
        objectives: ["理解绝对值的定义", "能用绝对值表示距离", "解决含绝对值的简单问题"],
        motivation: "从家到学校走了3公里。无论往东走还是往西走，距离都是3公里。关键在于距离，不考虑方向。绝对值就表达了「与0的距离」。",
        intuition: "对于数轴上的一个点，绝对值就是它离原点的距离。|-5|=5 意思是-5这个点离原点5个单位。|5|=5 同理。所以|a|永远是\u22650的。",
        definition: "实数a的绝对值记作|a|：当a\u22650时，|a|=a；当a<0时，|a|=-a。几何意义上，|a|表示数轴上点a到原点0的距离。|a-b|表示a与b之间的距离。",
        formulaLatex: "|a| = \\begin{cases} a, & a \\geq 0 \\\\ -a, & a < 0 \\end{cases}",
        formulaExplanation: "这个分段公式表示：如果数本身\u22650，绝对值就是它自己；如果a<0，绝对值是a的相反数（把负变正）。",
        conditions: "|a|总是\u22650。当且仅当a=0时，|a|=0。|-a|=|a|（相反数的绝对值相等）。",
        example: {
          problem: "已知 |x-2|=5，求x的值。",
          steps: [
            { description: "|x-2|=5 意味着x-2与0的距离是5", latex: "x-2 = 5 \\ \\text{或}\\ x-2 = -5" },
            { description: "当x-2=5时", latex: "x = 7" },
            { description: "当x-2=-5时", latex: "x = -3" },
            { description: "综上所述", latex: "x = 7 \\ \\text{或}\\ x = -3" },
          ],
          answer: "x=7 或 x=-3",
          answerLatex: "x = 7 \\ \\text{或}\\ x = -3",
        },
        commonMistakes: [
          { mistake: "解|x|=a时漏掉负解", correction: "|x|=a (a>0) 有两个解：x=a和x=-a。" },
          { mistake: "认为|a+b|=|a|+|b|", correction: "这是不成立的。例如|(-2)+3|=|1|=1，而|(-2)|+|3|=5。" },
        ],
        summary: ["绝对值=数轴上点到原点的距离", "|a|\u22650恒成立", "|a-b|表示a与b之间的距离"],
        selfCheck: ["|(-5)-(-2)|等于多少？几何意义是什么？", "解方程 |2x+1|=7。有多少个解？"],
      },
      {
        id: "num-polynomial", chapterId: "numbers", title: "整式运算与乘法公式",
        objectives: ["掌握整式的加减乘除运算", "熟练运用平方差公式和完全平方公式", "理解合并同类项"],
        motivation: "一块正方形花坛，边长是(a+b)米。想铺地板砖，需要计算面积。(a+b)\u00B2 等于多少？如果直接拆开算，就得到 a\u00B2 + 2ab + b\u00B2。这就是完全平方公式。",
        intuition: "乘法公式是简化计算的神器。比如99\u00B2不用硬乘——看作(100-1)\u00B2=10000-200+1=9801。公式不是要背的，而是要在实践中用起来。",
        definition: "平方差公式：(a+b)(a-b)=a\u00B2-b\u00B2。完全平方公式：(a+b)\u00B2=a\u00B2+2ab+b\u00B2，(a-b)\u00B2=a\u00B2-2ab+b\u00B2。合并同类项：字母和指数相同的项称为同类项，可以把系数相加合并。",
        formulaLatex: "(a+b)(a-b) = a^2 - b^2 \\\\ (a \\pm b)^2 = a^2 \\pm 2ab + b^2",
        formulaExplanation: "平方差：两个数的和乘以它们的差，等于这两个数的平方差。完全平方：(a+b)\u00B2展开有三项：两个平方项加（或减）两倍的交叉项。",
        conditions: "平方差公式中，两个括号内一项相同、一项互为相反数。完全平方公式中，a和b可以是任意实数或代数式。",
        example: {
          problem: "用公式计算 201 \u00D7 199。",
          steps: [
            { description: "201=200+1，199=200-1，符合平方差公式", latex: "(200+1)(200-1)" },
            { description: "应用平方差公式", latex: "= 200^2 - 1^2" },
            { description: "计算结果", latex: "= 40000 - 1 = 39999" },
          ],
          answer: "39999",
          answerLatex: "39999",
        },
        commonMistakes: [
          { mistake: "使用平方差时忘记先判断形式", correction: "必须保证两项相同、两项互为相反数才能用平方差。" },
          { mistake: "完全平方忘记2ab这一项", correction: "(a+b)\u00B2\u2260a\u00B2+b\u00B2！中间必须加2ab。这是最常见的错误。" },
        ],
        summary: ["平方差：(a+b)(a-b)=a\u00B2-b\u00B2", "完全平方：(a\u00B1b)\u00B2=a\u00B2\u00B12ab+b\u00B2", "合并同类项=系数相加、字母不变"],
        selfCheck: ["计算 103\u00B2 用完全平方公式。", "(2x+3y)(2x-3y) 等于多少？"],
      },
      {
        id: "num-factorization", chapterId: "numbers", title: "因式分解",
        objectives: ["理解因式分解是将多项式写成乘积形式", "掌握提取公因式法", "掌握公式法（平方差、完全平方）"],
        motivation: "把一个数字12拆成3\u00D74，是因为3和4是12的因数。对于代数式也是一样——把x\u00B2-4拆成(x+2)(x-2)，能帮助解方程（什么情况下乘积为0？每个因式为0时）",
        intuition: "因式分解就像把打包的东西拆开：把加法形式的式子变成乘法形式。为什么有用？因为乘积=0时，至少一个因式为0——这是解方程的关键思想。",
        definition: "因式分解：把一个多项式转化为几个整式的乘积的形式。方法一：提取公因式（如ax+ay=a(x+y)）。方法二：公式法（用平方差和完全平方公式的逆用）。",
        formulaLatex: "ma + mb = m(a + b) \\\\ a^2 - b^2 = (a+b)(a-b) \\\\ a^2 \\pm 2ab + b^2 = (a \\pm b)^2",
        formulaExplanation: "提取公因式是分配律的逆运用；公式法是平方差和完全平方公式的逆运用。",
        conditions: "提取公因式需先确定各项的最大公因式。完全平方式需先验证中间项是否为2ab。",
        example: {
          problem: "分解因式：x\u00B2 - 6x + 9。",
          steps: [
            { description: "识别：x\u00B2和9都是完全平方式", latex: "x^2 - 6x + 9" },
            { description: "验证：(-6x)是否为-2\u00D7x\u00D73", latex: "-2 \\cdot x \\cdot 3 = -6x \\ \\checkmark" },
            { description: "应用完全平方公式", latex: "(x - 3)^2" },
          ],
          answer: "(x-3)\u00B2",
          answerLatex: "(x-3)^2",
        },
        commonMistakes: [
          { mistake: "提取公因式时不完整", correction: "提取的应该是最大公因式。如6x+9=3(2x+3)，而不是2(3x+4.5)。" },
          { mistake: "公式法方向搞反", correction: "因式分解是a\u00B2-b\u00B2\u2192(a+b)(a-b)（展开的逆过程），不是反过来。" },
        ],
        summary: ["因式分解=和\u2192积的变换", "提取公因式=找最大公因式", "公式法=平方差和完全平方的逆用"],
        selfCheck: ["分解因式：3x\u00B2-12。第一步应该做什么？", "x\u00B2+4x+4 可以分解吗？如何分解？"],
      },
    ],
  },
  {
    id: "equations", number: 2, title: "方程与方程组",
    description: "从一元一次方程到二元方程组和一元二次方程，系统学习方程的解法思想和实际应用。",
    prerequisites: ["数与式", "整式运算", "因式分解"],
    teachingPoints: ["等式的性质是解方程的基础", "消元思想是解方程组的核心", "二次方程有三种解法：因式分解、配方法、公式法"],
    commonMisconceptions: ["方程的变形忘记了等式性质", "解分式方程后忘记检验增根", "二次方程判别式使用时机不对"],
    discussionQuestions: ["为什么两边同时加同一个数，等式仍然成立？", "什么情况下二元一次方程组没有唯一解？"],
    knowledgePoints: [
      {
        id: "eq-linear-one", chapterId: "equations", title: "一元一次方程",
        objectives: ["掌握一元一次方程的解法（移项、合并同类项、系数化为1）", "能检验方程的解", "用方程解决简单的实际问题"],
        motivation: "妈妈买了3斤苹果和2斤橘子，一共花了29元。已知橘子的单价是4元/斤，苹果多少钱一斤？假设苹果x元/斤：3x+2\u00D74=29。解开x=7。方程就是这样来帮助解决实际问题的。",
        intuition: "解方程就像天平游戏：天平两边本来平衡（等式成立）。要找到未知的重量（未知数），我们只能在天平两边做同等的加减——加同样的重量或减同样的重量——才能保持平衡。",
        definition: "一元一次方程的标准形式是ax+b=0（a\u22600）。解法步骤：(1)移项—含未知数的项移到等号一边；(2)合并同类项；(3)系数化为1——两边同除以a。",
        formulaLatex: "ax + b = 0 \\ \\Rightarrow \\ ax = -b \\ \\Rightarrow \\ x = -\\frac{b}{a}",
        formulaExplanation: "第一步将常数项b移到右边(-b)；第二步两边除以a得到解。a\u22600是非常重要的前提。",
        conditions: "a\u22600时方程有唯一解。当a=0且b\u22600时无解（矛盾）。当a=0且b=0时有无数解（恒成立）。",
        example: {
          problem: "解方程：3(x-2)+1=2x+5。",
          steps: [
            { description: "去括号", latex: "3x - 6 + 1 = 2x + 5" },
            { description: "合并左边常数项", latex: "3x - 5 = 2x + 5" },
            { description: "移项：2x移到左边，-5移到右边", latex: "3x - 2x = 5 + 5" },
            { description: "合并", latex: "x = 10" },
            { description: "检验：左边3(10-2)+1=25，右边20+5=25", latex: "25 = 25 \\ \\checkmark" },
          ],
          answer: "x=10",
          answerLatex: "x = 10",
        },
        commonMistakes: [
          { mistake: "移项时忘记改变符号", correction: "将项从一边移到另一边时，符号必须变化（加变减、减变加）。" },
          { mistake: "去括号时符号弄错", correction: "注意括号前的负号：-(2x-3)=-2x+3。" },
        ],
        summary: ["解方程的根据是等式的性质", "步骤：去分母\u2192去括号\u2192移项\u2192合并\u2192系数化为1\u2192检验", "a\u22600时ax+b=0有唯一解"],
        selfCheck: ["解方程：2x+7=3x-4。", "如果3x+1=3x-2，解是什么？"],
      },
      {
        id: "eq-system-two", chapterId: "equations", title: "二元一次方程组",
        objectives: ["掌握代入消元法", "掌握加减消元法", "用方程组解决实际问题"],
        motivation: "鸡兔同笼：头一共35个，脚一共94只。鸡和兔各几只？设鸡x只、兔y只。可列方程组{x+y=35, 2x+4y=94}。消元后得到x=23, y=12。",
        intuition: "两个未知数、两个方程，通常可以消去一个未知数，变成只有一个未知数的方程来解决。消元就像两个有重叠信息的线索——利用其中一个线索消掉另一个的未知部分。",
        definition: "二元一次方程组：{a\u2081x+b\u2081y=c\u2081, a\u2082x+b\u2082y=c\u2082}。代入法：从一个方程解出一个变量，代入另一个方程。加减法：将两个方程适当乘以系数后相加或相减，消去一个未知数。",
        formulaLatex: "\\begin{cases} a_1x + b_1y = c_1 \\\\ a_2x + b_2y = c_2 \\end{cases}",
        formulaExplanation: "代入法：由\u2460得x=(c\u2081-b\u2081y)/a\u2081，代入\u2461解出y，再回代求x。加减法：使x（或y）系数的绝对值相同，然后相加或相减。",
        conditions: "当系数矩阵的行列式\u22600时，方程组有唯一解。当行列式=0时，可能有无穷多解或无解。",
        example: {
          problem: "解方程组：{2x+y=7, x-y=2}。",
          steps: [
            { description: "两式相加：y+(-y)抵消", latex: "(2x+y)+(x-y) = 7+2" },
            { description: "得到关于x的方程", latex: "3x = 9" },
            { description: "解出x", latex: "x = 3" },
            { description: "代入\u2461求y", latex: "3 - y = 2 \\Rightarrow y = 1" },
            { description: "检验：2\u00D73+1=7，3-1=2", latex: "\\checkmark" },
          ],
          answer: "x=3, y=1",
          answerLatex: "x = 3, \\ y = 1",
        },
        commonMistakes: [
          { mistake: "加减消元时忘记将等式两边都乘以相同的数", correction: "给方程乘以一个数时，两边都要乘（包括常数项）。" },
          { mistake: "消元后忘记代入回去求另一个未知数", correction: "解出一个变量后必须回代求出第二个变量，答案才算完整。" },
        ],
        summary: ["消元思想：减少未知数的个数", "代入法适合一个方程已经解出一个变量的情况", "加减法适合同一个变量的系数成比例的情况"],
        selfCheck: ["解方程组：{3x+2y=12, x-y=1}。", "什么情况下加减法比代入法更好用？"],
      },
      {
        id: "eq-quadratic", chapterId: "equations", title: "一元二次方程",
        objectives: ["能用因式分解法解一元二次方程", "掌握求根公式", "理解判别式与根的数量关系"],
        motivation: "投掷一个篮球，它经过的路线是抛物线——轨迹可以用二次函数描述。想知道球在什么高度、什么时间触地，就需要解二次方程。",
        intuition: "二次方程最多有两个根（x轴上的截点）。判别式\u0394告诉你根的情况：\u0394>0两个不同根、\u0394=0一个根（重根）、\u0394<0没有实数根。",
        definition: "一元二次方程标准形式：ax\u00B2+bx+c=0（a\u22600）。求根公式：x=(-b\u00B1\u221A(b\u00B2-4ac))/(2a)。判别式\u0394=b\u00B2-4ac决定根的情况。",
        formulaLatex: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a} \\\\ \\Delta = b^2 - 4ac",
        formulaExplanation: "求根公式由一个有理部分(-b/(2a))加上或减去一个根号部分(\u221A\u0394/(2a))组成。\u0394的正负决定了根号内是否非负——即有没有实数根。",
        conditions: "a\u22600。\u0394>0\u2192两个不等实根；\u0394=0\u2192一个实根（重根）；\u0394<0\u2192无实数根。",
        example: {
          problem: "解方程：x\u00B2 - 5x + 6 = 0。",
          steps: [
            { description: "识别a=1,b=-5,c=6", latex: "a=1, b=-5, c=6" },
            { description: "计算判别式", latex: "\\Delta = 25 - 24 = 1 > 0" },
            { description: "代入求根公式", latex: "x = \\frac{5 \\pm \\sqrt{1}}{2} = \\frac{5 \\pm 1}{2}" },
            { description: "两个根", latex: "x_1 = 3, \\ x_2 = 2" },
            { description: "或用因式分解法：(x-2)(x-3)=0", latex: "x=2 \\text{ 或 } x=3" },
          ],
          answer: "x\u2081=2, x\u2082=3",
          answerLatex: "x_1 = 2, \\ x_2 = 3",
        },
        commonMistakes: [
          { mistake: "求根公式中忘写负号", correction: "分子是(-b)不是b，如果有负号不能忘。" },
          { mistake: "误认为x\u00B2=k的解只有\u221Ak", correction: "x\u00B2=k(k>0)有两个解：x=\u00B1\u221Ak。" },
        ],
        summary: ["ax\u00B2+bx+c=0 的求根公式：x=(-b\u00B1\u221A\u0394)/(2a)", "\u0394>0两实根 | \u0394=0一实根 | \u0394<0无实根", "能因式分解的先因式分解，不能的用求根公式"],
        selfCheck: ["解方程：x\u00B2+2x-3=0。", "什么时候\u0394<0？举一个这样的二次方程。"],
      },
    ],
  },
  {
    id: "inequalities", number: 3, title: "不等式",
    description: "从等式扩展到不等式，学习不等式的性质、一元一次不等式（组）的解法。",
    prerequisites: ["一元一次方程", "数轴", "整式运算"],
    teachingPoints: ["不等式与等式的性质和变形有本质不同", "乘除负数时不等号方向必须改变", "不等式组的解集是各不等式解集的公共部分"],
    commonMisconceptions: ["忘记乘除负数时改变不等号方向", "误把开区间写成闭区间", "不等式两边同时平方时不注意符号"],
    discussionQuestions: ["为什么乘除负数时不等号要改变方向？", "什么情况下两个不等式的解集正好相反？"],
    knowledgePoints: [
      {
        id: "ineq-properties", chapterId: "inequalities", title: "不等式的基本性质",
        objectives: ["掌握不等式的基本性质", "理解乘除负数时不等号为何改变", "能正确变形不等式"],
        motivation: "超市的购物袋最多装5公斤。如果你已经装了3.2公斤，最多还能装多少？3.2+x\u22645。这与方程不同——答案是x\u22641.8（不超过1.8公斤），而不是恰好等于某个值。",
        intuition: "不等式的性质与等式有相同点也有不同点。两边加同一个数——方向不变（和等式一样）。但两边乘以一个负数时——方向反转！Why？因为数轴上的点左右关系被翻面了。",
        definition: "不等式的基本性质：(1)两边加（减）同一个数，不等号方向不变；(2)两边乘（除）同一个正数，方向不变；(3)两边乘（除）同一个负数，方向改变。",
        formulaLatex: "\\text{若 } a < b: \\quad a+c < b+c, \\ a-c < b-c \\\\ a \\cdot c < b \\cdot c \\ (c > 0), \\quad a \\cdot c > b \\cdot c \\ (c < 0)",
        formulaExplanation: "性质(1)是不等号保持不变的情况。性质(3)是关键：乘以或除以负数时，大小关系反转（小变大、大变小）。",
        conditions: "注意：两边乘（除）以0是不允许的。两边平方时，如果符号不确定，不能直接比较。",
        example: {
          problem: "已知a<b，比较-2a与-2b的大小。",
          steps: [
            { description: "由a<b，两边同乘-2（负数）", latex: "a < b" },
            { description: "乘负数后不等号反转", latex: "-2a > -2b" },
          ],
          answer: "-2a > -2b",
          answerLatex: "-2a > -2b",
        },
        commonMistakes: [
          { mistake: "两边乘-2后写-2a<-2b（忘记反转不等号）", correction: "乘负数时不等号必须反转。取a=1,b=2验证：-2>-4。" },
          { mistake: "两边同时乘以未知量时不知道符号", correction: "如果未知量的正负不能确定，不能直接乘。需要分情况讨论。" },
        ],
        summary: ["加/减同一个数：方向不变", "乘/除正数：方向不变", "乘/除负数：方向反转（关键！）"],
        selfCheck: ["已知x<y，比较-3x+1和-3y+1的大小。", "为什么不等号在乘负数时反转？用具体数字解释。"],
      },
      {
        id: "ineq-linear-one", chapterId: "inequalities", title: "一元一次不等式",
        objectives: ["掌握一元一次不等式的解法和步骤", "能用数轴正确表示解集", "理解开区间和闭区间"],
        motivation: "公交车上现有人数50人。要保证不超载，还能上多少人？设还能上x人：50+x\u2264120。解得x\u226470。不等式帮我们找到允许的范围而不是唯一解。",
        intuition: "解不等式和解方程方法很相似——移项、合并。唯一的关键区别是：如果最后一步系数是负数，除以它后不等号要反转。这就像数轴上的镜像翻转。",
        definition: "一元一次不等式的解法：(1)去分母；(2)去括号；(3)移项；(4)合并同类项；(5)系数化为1：除系数时，如果是正数不等号不变，负数则反转。",
        formulaLatex: "ax + b > 0 \\quad (a \\neq 0)",
        formulaExplanation: "如果a>0，解集是x>-b/a。如果a<0，解集是x<-b/a（不等号反转）。用数轴上的空心/实心圆表示。",
        conditions: "系数a\u22600。画数轴时，含等号用实心圆（闭区间），不含等号用空心圆（开区间）。",
        example: {
          problem: "解不等式：-2x+3\u22647，并在数轴上表示解集。",
          steps: [
            { description: "移项", latex: "-2x \\leq 7 - 3" },
            { description: "整理", latex: "-2x \\leq 4" },
            { description: "系数化为1：除以-2（负数）反转不等号", latex: "x \\geq -2" },
            { description: "数轴表示：在-2处实心圆，向右画箭头", latex: "[-2, +\\infty)" },
          ],
          answer: "x \u2265 -2",
          answerLatex: "x \\geq -2",
        },
        commonMistakes: [
          { mistake: "在-2x\u22644这步，除以-2后忘记反转不等号", correction: "因为-2<0，除以负数时不等号方向必须改变。" },
          { mistake: "画数轴时，\u2265错用空心圆", correction: "含等号(\u2265或\u2264)用实心圆，不含等号(>或<)用空心圆。" },
        ],
        summary: ["解不等式的步骤与解方程类似", "除以负数时不等号反转！", "数轴表示：空心=不包含、实心=包含"],
        selfCheck: ["解不等式：3x-5>10。", "-4x+1\u22659的解集是什么？在数轴上表示。"],
      },
      {
        id: "ineq-system", chapterId: "inequalities", title: "一元一次不等式组",
        objectives: ["理解不等式组解集是各不等式解集的公共部分", "能用数轴找出解集", "解决含不等式组的实际问题"],
        motivation: "学生宿舍要同时满足：(1)总面积不超过50m\u00B2；(2)每间至少15m\u00B2。设面积x，则15\u2264x\u226450。这就是两个不等式的共同范围。",
        intuition: "不等式组的解集=各个不等式的解集的交集。想象每个人都在数轴上画自己的领地（允许范围），公共领地就是所有人的领地重合的地方。",
        definition: "几个一元一次不等式联立构成不等式组。不等式组的解集是使得每个不等式都成立的x的集合。解法：分别解每个不等式，然后在数轴上找出重叠区域。",
        formulaLatex: "\\begin{cases} a_1 x + b_1 > 0 \\\\ a_2 x + b_2 > 0 \\end{cases} \\quad \\text{解集为交集}",
        formulaExplanation: "先分别解出两个不等式的解集，然后在同一个数轴上画出，找出重叠区域就是不等式组的解集。",
        conditions: "交集是各个解集的公共部分。如果两个解集不相交，不等式组无解。",
        example: {
          problem: "解不等式组：{x+2>3, 2x-1\u22645}。",
          steps: [
            { description: "解第一个", latex: "x > 1" },
            { description: "解第二个", latex: "2x \\leq 6 \\Rightarrow x \\leq 3" },
            { description: "找公共部分", latex: "1 < x \\leq 3" },
          ],
          answer: "1 < x \u2264 3",
          answerLatex: "1 < x \\leq 3",
        },
        commonMistakes: [
          { mistake: "将解集写作两个解集的并集", correction: "不等式组的解集是交集（公共部分），不是并集。" },
          { mistake: "分别解完后没有在数轴上合并表示", correction: "只在数轴上画出两个解集的重叠区域，才是最终答案。" },
        ],
        summary: ["不等式组=多个不等式同时成立", "解集=各不等式解集的交集", "数轴画法：先分别画再找重叠区"],
        selfCheck: ["解不等式组：{x-3\u22650, 2x+1<9}。", "什么情况导致不等式组无解？"],
      },
    ],
  },
  {
    id: "functions", number: 4, title: "函数及其图像",
    description: "从变量关系引入函数概念，系统学习一次函数、反比例函数和二次函数的图像、性质和应用。",
    prerequisites: ["平面直角坐标系", "方程与不等式", "整式运算"],
    teachingPoints: ["函数是研究两个变量之间关系的工具", "一次函数y=kx+b的图像是直线", "二次函数的图像是抛物线，顶点和对称轴是核心"],
    commonMisconceptions: ["混淆自变量和因变量", "k>0就认为过一三象限（一次函数中k只决定单调性）", "二次函数配方时算错"],
    discussionQuestions: ["为什么k=0时y=b仍然是一条直线？", "y=2x+1和y=2x-3有什么关系？"],
    knowledgePoints: [
      {
        id: "func-concept", chapterId: "functions", title: "变量、函数与函数的表示",
        objectives: ["理解自变量和因变量的概念", "掌握函数的三种表示方法", "能判断给定的关系是否为函数"],
        motivation: "买苹果：每斤3元。买的斤数x决定了总价y=3x。y随着x的变化而变化——x叫自变量（自己决定），y叫因变量（依赖于x）。这就是函数的最简单例子。",
        intuition: "函数就像一台自动售货机：你选择投入什么（输入x），机器按照某种规则产出结果（输出y）。输入可以是任何数，但输出总是唯一确定的一个数。",
        definition: "函数：在一个变化过程中，有两个变量x和y。如果对于x的每一个值，y都有唯一确定的值与之对应，则称y是x的函数。x称为自变量，y是因变量。函数的三种表示法：解析式法、列表法、图像法。",
        formulaLatex: "y = f(x), \\quad x \\in \\text{定义域}",
        formulaExplanation: "f是函数名，括号内的x是自变量，整个f(x)表示因变量的值。定义域是自变量的取值范围。",
        conditions: "一个输入对应恰好一个输出才是函数。但不同的输入可以有相同的输出。",
        example: {
          problem: "判断下列关系是否函数：y\u00B2=x。",
          steps: [
            { description: "当x=4时", latex: "y^2 = 4 \\Rightarrow y = 2 \\text{ 或 } y = -2" },
            { description: "一个x对应两个不同的y值", latex: "\\text{不是唯一确定的}" },
            { description: "所以y\u00B2=x不是函数", latex: "\\text{y不是x的函数}" },
          ],
          answer: "不是函数",
          answerLatex: "y^2 = x \\text{ 中 y 不是 x 的函数}",
        },
        commonMistakes: [
          { mistake: "以为所有方程都是函数", correction: "y\u00B2=x这样使得一个x对应多个y的方程不是函数。关键是唯一对应。" },
          { mistake: "混淆自变量和因变量", correction: "y=f(x)中括号里的是自变量（自由的），左边的是因变量（受限的）。" },
        ],
        summary: ["函数：每个输入对应唯一输出", "三种表示法：解析式、表格、图像", "不是所有方程都是函数"],
        selfCheck: ["辨别y=|x|是不是函数？y=x\u00B2呢？", "写出一个x对应两个y的例子（不是函数）。"],
      },
      {
        id: "func-linear", chapterId: "functions", title: "正比例函数和一次函数",
        objectives: ["掌握y=kx的图像是过原点的直线", "掌握y=kx+b的图像", "理解k和b的几何意义"],
        motivation: "出租车起步费8元，每公里加收3元。行驶x公里后，费用y=3x+8。这是一个一次函数——图像是一条直线。k=3是单价（斜率），b=8是起步价（截距）。",
        intuition: "一次函数的图像总是直线。k控制陡不陡（斜率=上升速度），b控制从哪里开始（y截距）。k>0则函数上升，k<0则下降。",
        definition: "正比例函数y=kx(k\u22600)是一次函数y=kx+b(b=0)的特殊情况。一次函数的图像是直线。k>0：y随x增大而增大（单调递增）；k<0：y随x增大而减小（单调递减）。b是y截距。",
        formulaLatex: "y = kx + b \\quad (k \\neq 0) \\\\ k = \\frac{y_2 - y_1}{x_2 - x_1}, \\quad b = y - kx",
        formulaExplanation: "k表示x每增加1时y的变化量。b是x=0时y的值（图像与y轴的交点的y坐标）。",
        conditions: "k\u22600时是一次函数。k=0时y=b是常数函数（水平线）。x\u2081\u2260x\u2082（两点不能垂直对齐）。",
        example: {
          problem: "已知一次函数过点(2,5)和(4,9)，求其解析式。",
          steps: [
            { description: "用斜率公式求k", latex: "k = \\frac{9-5}{4-2} = \\frac{4}{2} = 2" },
            { description: "用点斜式求b", latex: "y = 2x + b, \\ 5 = 2\\times2 + b \\Rightarrow b = 1" },
            { description: "写出解析式", latex: "y = 2x + 1" },
          ],
          answer: "y = 2x + 1",
          answerLatex: "y = 2x + 1",
        },
        commonMistakes: [
          { mistake: "把k当成直线与x轴的夹角", correction: "k是斜率（纵变/横变），不是角度。仅当坐标轴比例相同时，k才等于tan(角度)。" },
          { mistake: "用k=(x\u2082-x\u2081)/(y\u2082-y\u2081)计算", correction: "k是纵坐标差除以横坐标差，即(y\u2082-y\u2081)/(x\u2082-x\u2081)。" },
        ],
        summary: ["y=kx+b的k是斜率，b是y截距", "k>0递增，k<0递减", "两点确定一条直线的k和b"],
        selfCheck: ["直线y=-3x+2是递增还是递减？", "求过点(0,-1)和(2,3)的一次函数解析式。"],
      },
      {
        id: "func-quadratic", chapterId: "functions", title: "二次函数",
        objectives: ["理解二次函数y=ax\u00B2+bx+c的图像是抛物线", "掌握顶点坐标公式", "判断开口方向和最大最小值"],
        motivation: "你发射一个水火箭。回落到地面之前，它的高度h与时间t的关系是二次曲线——有最高点（顶点）。二次函数让抛射物轨迹得以表达。",
        intuition: "二次函数的图像是一条对称的U形曲线（抛物线）。a>0时抛物线口向上（像碗），有最低点；a<0时口向下（像山），有最高点。",
        definition: "二次函数的一般形式：y=ax\u00B2+bx+c(a\u22600)。顶点坐标：(-b/(2a), (4ac-b\u00B2)/(4a))。对称轴：x=-b/(2a)。a>0则开口向上且有最小值，a<0则开口向下且有最大值。",
        formulaLatex: "y = ax^2 + bx + c \\quad (a \\neq 0) \\\\ x_v = -\\frac{b}{2a}, \\quad y_v = \\frac{4ac - b^2}{4a}",
        formulaExplanation: "a的符号决定开口方向。b与对称轴位置有关。c是y截距。顶点公式从配方法推导而来。",
        conditions: "a\u22600。\u0394=b\u00B2-4ac决定与x轴交点：\u0394>0两点，\u0394=0一点，\u0394<0无交点。",
        example: {
          problem: "求y=x\u00B2-4x+3的顶点坐标和对称轴。",
          steps: [
            { description: "顶点x坐标", latex: "x_v = -\\frac{-4}{2\\times1} = 2" },
            { description: "顶点y坐标", latex: "y_v = 2^2 - 4\\times2 + 3 = -1" },
            { description: "顶点(2,-1)，对称轴x=2", latex: "\\text{顶点}(2,-1), \\text{对称轴} x=2" },
          ],
          answer: "顶点(2,-1)，对称轴x=2",
          answerLatex: "\\text{顶点}(2,-1), \\ x=2",
        },
        commonMistakes: [
          { mistake: "顶点公式中-4ac搞成+4ac", correction: "顶点y坐标=(4ac-b\u00B2)/(4a)，注意中间是减号。" },
          { mistake: "把对称轴写成y=-b/(2a)", correction: "对称轴是竖直线，方程是x=-b/(2a)。" },
        ],
        summary: ["二次函数图像=抛物线", "顶点=最值点=对称轴与抛物线的交点", "a>0开口向上，a<0开口向下"],
        selfCheck: ["y=-x\u00B2+2x+1的顶点在哪里？开口方向是什么？", "二次函数什么时候与x轴没有交点？"],
      },
    ],
  },
  {
    id: "plane-geometry", number: 5, title: "平面几何",
    description: "研究平面图形的性质和关系：点、线、角、三角形全等、四边形、勾股定理。",
    prerequisites: ["角的概念", "平行线的认识", "三角形的基本概念"],
    teachingPoints: ["几何需要逻辑推理和严密表达", "全等三角形是证明边和角相等的重要工具", "勾股定理是直角三角形中最重要的关系"],
    commonMisconceptions: ["混淆全等的判定条件（AAA不能证明全等）", "勾股定理只在直角三角形中成立", "混淆角的平分线和线段的垂直平分线"],
    discussionQuestions: ["为什么AAA不能证明三角形全等？举出反例。", "勾股定理有几种证明方法？"],
    knowledgePoints: [
      {
        id: "geo-basics", chapterId: "plane-geometry", title: "点、线、角及平行线",
        objectives: ["理解线段、射线和直线的区别", "掌握对顶角、邻补角和同位角", "理解平行线的性质和判定"],
        motivation: "在导航中，沿着某路直走，在路口左转——这些操作都是几何描述。平行（不交汇的两条路）和垂直（十字路口）构成了平面几何的基础。",
        intuition: "把两条平行线想象成铁路的两条钢轨——它们永远保持相同的距离，永不汇合。两条相交直线在一点上交叉，形成四个角。",
        definition: "两点确定一条线段（有长度），线段可以延伸为射线或直线。对顶角相等。同位角、内错角和同旁内角是判定两条直线平行的条件。",
        formulaLatex: "\\text{对顶角：}\\angle 1 = \\angle 3 \\\\ \\text{平行：}\\angle \\text{同位} = \\angle \\text{同位}",
        formulaExplanation: "对顶角是两条相交直线中不相邻的两个角，它们总是相等。",
        conditions: "判定平行：同位角相等、内错角相等或同旁内角互补，三种条件有其一即可判定两直线平行。",
        example: {
          problem: "已知直线AB\u2225CD，\u22201=65\u00B0，求同位角\u22202的度数。",
          steps: [
            { description: "AB\u2225CD时，同位角相等", latex: "\\angle 2 = \\angle 1" },
            { description: "所以\u22202=65\u00B0", latex: "\\angle 2 = 65^\\circ" },
          ],
          answer: "65\u00B0",
          answerLatex: "65^\\circ",
        },
        commonMistakes: [
          { mistake: "混淆同位角和内错角", correction: "同位角在两条平行线的同一侧且位置相同；内错角在两条线之间且交错。" },
          { mistake: "认为两条直线不平行就没有同位角概念", correction: "同位角总存在，但只有在两条直线平行时它们才相等。" },
        ],
        summary: ["对顶角相等（总是成立）", "平行线\u2192同位角相等（必要条件）", "同位角相等\u2192平行线（充分条件）"],
        selfCheck: ["如何只用同位角判定两条直线平行？", "两条平行线被一条直线所截，\u22201=70\u00B0，求同位角。"],
      },
      {
        id: "geo-congruence", chapterId: "plane-geometry", title: "三角形全等",
        objectives: ["掌握全等三角形的定义", "掌握五种全等判定方法", "能运用全等证明边相等和角相等"],
        motivation: "建筑师需要检查两块三角板是否完全一样——能不能重合在一起？全等三角形就是形状和大小完全相同的两个三角形。",
        intuition: "两个三角形全等的意思是：你拿起一个三角形，经过平移、旋转或翻转，能完全盖在另一个上面。五种判定方法是最少信息规则。",
        definition: "能够完全重合的两个三角形称为全等三角形，记作\u25B3ABC\u2245\u25B3DEF。判定条件：SSS（三边）、SAS（两边夹角）、ASA（两角夹边）、AAS（两角非夹边）、HL（直角三角形的斜边和直角边）。",
        formulaLatex: "\\text{SSS: }AB=DE, BC=EF, AC=DF \\Rightarrow \\triangle ABC \\cong \\triangle DEF",
        formulaExplanation: "SSS是三边对应相等的简写。AAA不能判定全等（只能判定相似）。SSA一般不能判定全等。",
        conditions: "每个判定条件必须包含至少一条边的信息。SSA一般不能判定全等。",
        example: {
          problem: "已知AB=DE，\u2220A=\u2220D，AC=DF。证明\u25B3ABC\u2245\u25B3DEF。",
          steps: [
            { description: "已知条件", latex: "AB = DE, \\angle A = \\angle D, AC = DF" },
            { description: "符合SAS条件", latex: "\\text{SAS判定}" },
            { description: "所以三角形全等", latex: "\\triangle ABC \\cong \\triangle DEF" },
          ],
          answer: "SAS判定",
          answerLatex: "\\triangle ABC \\cong \\triangle DEF \\ (SAS)",
        },
        commonMistakes: [
          { mistake: "认为AAA能判定全等", correction: "AAA只能判定相似（形状相同），但大小可以不同。" },
          { mistake: "把SSA当作判定条件使用", correction: "SSA一般不能判定全等，因为有两种可能的三角形形状。" },
        ],
        summary: ["全等=形状和大小完全相同", "5种判定：SSS、SAS、ASA、AAS、HL", "AAA不能判定全等（只能相似）"],
        selfCheck: ["写出所有全等三角形的判定方法。", "为什么SSA不能判定全等？画图说明。"],
      },
      {
        id: "geo-pythagorean", chapterId: "plane-geometry", title: "勾股定理",
        objectives: ["理解勾股定理的含义", "掌握勾股定理的计算公式", "会用勾股定理解决实际问题"],
        motivation: "古代埃及人在尼罗河三角洲测量土地时发现3\u00B2+4\u00B2=5\u00B2——这就是勾股定理的最初发现。",
        intuition: "对于一个直角三角形，如果以三条边为边长各做一个正方形，你会发现：两个小正方形的面积之和恰好等于大正方形的面积。",
        definition: "在直角三角形中，两直角边的平方和等于斜边的平方。若直角边为a和b，斜边为c，则有a\u00B2+b\u00B2=c\u00B2。逆定理：如果a\u00B2+b\u00B2=c\u00B2，则该三角形是直角三角形。",
        formulaLatex: "a^2 + b^2 = c^2",
        formulaExplanation: "a和b是直角边，c是斜边（最长边，对着直角的边）。逆定理同样成立。",
        conditions: "只适用于直角三角形。斜边必须是直角所对的边（最长边）。",
        example: {
          problem: "一个直角三角形的两条直角边分别为6和8，求斜边的长度。",
          steps: [
            { description: "应用勾股定理", latex: "c^2 = 6^2 + 8^2" },
            { description: "计算平方", latex: "c^2 = 36 + 64 = 100" },
            { description: "开方（取正值）", latex: "c = \\sqrt{100} = 10" },
          ],
          answer: "10",
          answerLatex: "c = 10",
        },
        commonMistakes: [
          { mistake: "把直角边和斜边弄反", correction: "勾股定理永远是直角边平方之和等于斜边的平方。" },
          { mistake: "开方后忘记舍去负根", correction: "边长总是正数，舍去负根。" },
        ],
        summary: ["勾股定理：a\u00B2+b\u00B2=c\u00B2（直角三角形）", "逆定理：如果a\u00B2+b\u00B2=c\u00B2，则是直角三角形"],
        selfCheck: ["已知直角边长为5和12，求斜边长。", "三角形的三边长为7,24,25，它是直角三角形吗？"],
      },
    ],
  },
  {
    id: "triangle-circle", number: 6, title: "三角形与圆",
    description: "深入学习相似三角形、锐角三角函数和圆的性质。",
    prerequisites: ["三角形全等", "勾股定理", "平面直角坐标系"],
    teachingPoints: ["相似三角形判定条件比全等更宽松", "锐角三角函数以角度为自变量", "圆是轴对称和中心对称图形"],
    commonMisconceptions: ["混淆相似和全等", "三角函数的单位搞错", "圆周角和圆心角关系记反"],
    discussionQuestions: ["为什么相似比总是正数？", "sin\u00B2A+cos\u00B2A=1如何证明？"],
    knowledgePoints: [
      {
        id: "tc-similar", chapterId: "triangle-circle", title: "相似三角形",
        objectives: ["掌握相似三角形的定义和判定方法", "能运用相似比解决边长问题"],
        motivation: "拍照片时，你和建筑物按比例缩小，但保持相同形状——这就是相似。",
        intuition: "两个三角形相似时，对应角相等，对应边成比例。相似比就是对应边之比。可以理解为三角板在复印机上放大或缩小。",
        definition: "相似三角形的判定：(1)两个角对应相等（AA）；(2)两组边对应成比例且夹角相等；(3)三组边对应成比例。全等三角形是相似比为1的特殊情况。",
        formulaLatex: "\\triangle ABC \\sim \\triangle DEF \\Longleftrightarrow \\frac{AB}{DE} = \\frac{BC}{EF} = \\frac{AC}{DF}",
        formulaExplanation: "符号~表示相似。对应边的比值都相等，这个比值叫相似比。",
        conditions: "相似比不能为零。对应的边和角必须严格对应。",
        example: {
          problem: "\u25B3ABC~\u25B3DEF，AB=3，DE=6，BC=4。求EF。",
          steps: [
            { description: "相似比=AB/DE=3/6=1/2（注意方向）", latex: "\\text{k} = \\frac{DE}{AB} = 2" },
            { description: "EF/BC=k", latex: "EF = 4 \\times 2 = 8" },
          ],
          answer: "EF=8",
          answerLatex: "EF = 8",
        },
        commonMistakes: [
          { mistake: "相似比写反", correction: "总是用大三角形的边除以小三角形的对应边。" },
        ],
        summary: ["相似=形状相同大小不同", "判定：AA、SAS(\u221D)、SSS(\u221D)", "面积比=相似比的平方"],
        selfCheck: ["两个角为30\u00B0和60\u00B0的三角形一定相似吗？", "如果相似比为2，面积比是多少？"],
      },
      {
        id: "tc-trig", chapterId: "triangle-circle", title: "锐角三角函数",
        objectives: ["理解正弦、余弦和正切的定义", "掌握特殊三角函数值", "会用三角函数解决实际问题"],
        motivation: "你站在山脚下仰望山顶，坡度为30\u00B0。坡度就是正切值tan30\u00B0。你离山脚50米，问山高多少？用tan公式就能算出来。",
        intuition: "在直角三角形中，每个锐角都有一个固定的对边/斜边的比值——这就是正弦。不论三角形的大小，这个比值只与角度有关。",
        definition: "在Rt\u25B3ABC中，\u2220C=90\u00B0。(1)sinA=对边/斜边=a/c；(2)cosA=邻边/斜边=b/c；(3)tanA=对边/邻边=a/b。",
        formulaLatex: "\\sin A = \\frac{a}{c}, \\quad \\cos A = \\frac{b}{c}, \\quad \\tan A = \\frac{a}{b}",
        formulaExplanation: "对边是角A对面的直角边，邻边是角A旁边的直角边（不是斜边）。c是斜边。",
        conditions: "仅适用于锐角（0\u00B0-90\u00B0之间）。sin\u00B2A+cos\u00B2A=1恒成立。",
        example: {
          problem: "在Rt\u25B3ABC中，\u2220C=90\u00B0，\u2220A=30\u00B0，斜边c=10。求b的长度。",
          steps: [
            { description: "cos30\u00B0=b/c，cos30\u00B0=\u221A3/2", latex: "\\cos30^\\circ = \\frac{\\sqrt{3}}{2}" },
            { description: "b = c\u00D7cos30\u00B0", latex: "b = 10 \\times \\frac{\\sqrt{3}}{2} = 5\\sqrt{3}" },
          ],
          answer: "b=5\u221A3",
          answerLatex: "b = 5\\sqrt{3}",
        },
        commonMistakes: [
          { mistake: "正弦和余弦的比值写反", correction: "正弦=对边/斜边，余弦=邻边/斜边。" },
          { mistake: "特殊三角函数值记错", correction: "sin从小到大(1/2\u2192\u221A3/2)，cos从大到小。" },
        ],
        summary: ["sin=对/斜，cos=邻/斜，tan=对/邻", "特殊角度需记忆(30/45/60\u00B0)", "sin\u00B2A+cos\u00B2A=1"],
        selfCheck: ["在Rt\u25B3中，\u2220A=45\u00B0、斜边=\u221A2，求sinA和cosA。", "tan60\u00B0等于多少？"],
      },
      {
        id: "tc-circle", chapterId: "triangle-circle", title: "圆的基本性质",
        objectives: ["理解圆心角、圆周角和弧的关系", "掌握垂径定理", "会求圆的周长和面积"],
        motivation: "车轮为什么是圆的？因为圆心到轮缘各点的距离相等，这样滚动起来才平稳。",
        intuition: "在圆上任意取两点A、B。从圆心O连到这两点形成的角叫圆心角；从圆周上任意点连到A、B的角叫圆周角。关键：同一个弧对应的圆周角总是圆心角的一半。",
        definition: "圆：到定点（圆心）距离等于定长（半径）的所有点的集合。C=2\u03C0r，S=\u03C0r\u00B2。圆周角=圆心角/2。",
        formulaLatex: "C = 2\\pi r, \\quad S = \\pi r^2 \\\\ \\text{圆周角} = \\frac{1}{2} \\times \\text{圆心角}",
        formulaExplanation: "r是半径。\u03C0\u22483.14。半圆的圆周角是90\u00B0。",
        conditions: "r>0。圆周角定理中等弧对应等圆周角和等圆心角。",
        example: {
          problem: "已知半径为5cm，求圆的周长和面积。",
          steps: [
            { description: "周长=C=2\u03C0\u00D75=10\u03C0cm", latex: "C = 10\\pi" },
            { description: "面积=S=\u03C0\u00D75\u00B2=25\u03C0cm\u00B2", latex: "S = 25\\pi" },
          ],
          answer: "C=10\u03C0\u224831.4cm, S=25\u03C0\u224878.5cm\u00B2",
          answerLatex: "C = 10\\pi, \\ S = 25\\pi",
        },
        commonMistakes: [
          { mistake: "面积公式误用2\u03C0r\u00B2", correction: "面积是\u03C0r\u00B2，周长是2\u03C0r。" },
          { mistake: "圆周角和圆心角的2倍关系用反", correction: "圆心角=2\u00D7圆周角。" },
        ],
        summary: ["C=2\u03C0r, S=\u03C0r\u00B2", "圆周角=1/2圆心角", "等弧\u2192等圆周角"],
        selfCheck: ["一个圆的半径为7cm，面积是多少？", "同一个弧上的所有圆周角都相等吗？为什么？"],
      },
    ],
  },
  {
    id: "statistics", number: 7, title: "统计与概率",
    description: "学习数据的收集、整理、分析和表达，掌握统计量和图表，理解随机事件和概率。",
    prerequisites: ["算术平均数", "分数与百分比"],
    teachingPoints: ["平均数、中位数和众数反映数据的集中趋势", "方差反映数据的离散程度", "概率是描述随机事件发生可能性的度量"],
    commonMisconceptions: ["平均数必然在数据范围内（可能不在）", "概率0的事件一定不会发生", "频率和概率是一回事"],
    discussionQuestions: ["为什么有时用中位数而不直接用平均数？", "抛硬币抛了10次都是正面，第11次概率怎么算？"],
    knowledgePoints: [
      {
        id: "stat-data", chapterId: "statistics", title: "数据收集与统计图表",
        objectives: ["掌握数据收集的方法", "能绘制和读解柱状图、折线图", "理解频数与频率"],
        motivation: "班级要决定春游地点。每个同学投票后，统计各选项的得票数。柱状图直观显示了哪个地方最受欢迎。",
        intuition: "数据就像一堆原材料，统计图表是把原材料加工成可观察的信息。柱状图适合比较各选项，折线图适合展示变化趋势。",
        definition: "频数：某个数据值出现的次数。频率：频数/总次数。频率之和等于1。",
        formulaLatex: "\\text{频率} = \\frac{\\text{频数}}{\\text{总次数}}",
        formulaExplanation: "频率介于0和1之间。所有频率加起来一定等于1（100%）。",
        conditions: "频数是非负整数。频率的和必须等于1。",
        example: {
          problem: "班上有24人，最喜爱的运动如下：足球8人、篮球6人、乒乓球4人、跑步4人、其他2人。求足球的频率。",
          steps: [
            { description: "频数=8", latex: "\\text{频数} = 8" },
            { description: "频率=8/24=1/3", latex: "\\text{频率} = \\frac{8}{24} = \\frac{1}{3}" },
          ],
          answer: "1/3 \u2248 33.3%",
          answerLatex: "\\frac{1}{3} \\approx 33.3\\%",
        },
        commonMistakes: [
          { mistake: "混淆频数和频率", correction: "频数是具体数字，频率是比值。" },
        ],
        summary: ["频数=出现多少次", "频率=频数/总数", "所有频率之和=1"],
        selfCheck: ["班上有30人，12人选篮球，频率是多少？"],
      },
      {
        id: "stat-measures", chapterId: "statistics", title: "平均数、中位数和众数",
        objectives: ["掌握平均数、中位数和众数的定义", "能根据数据分布选择合适的集中量度"],
        motivation: "一个富豪住进了一个小村庄，村庄的平均收入立刻飙升了十倍——但这不代表村庄变富裕了，只代表平均数被极端值拉高了。此时中位数才能反映典型情况。",
        intuition: "平均数=总和/n（易被极端值影响）。中位数=排序后中间位的数（不受极端值影响）。众数=出现最多次的数。",
        definition: "平均数=(x\u2081+...+x\u2099)/n。中位数：排序后中间位的数。众数：出现次数最多的数。",
        formulaLatex: "\\bar{x} = \\frac{x_1 + \\cdots + x_n}{n}",
        formulaExplanation: "平均数用符号x\u0304表示。中位数：n奇数时中间位；n偶数时取中间两数的平均值。",
        conditions: "平均数所有数据参与。中位数对极端值不敏感。",
        example: {
          problem: "一组数据: 65,70,72,75,78,80。求平均数和中位数。",
          steps: [
            { description: "平均数", latex: "\\frac{440}{6} \\approx 73.3" },
            { description: "中位数", latex: "\\frac{72+75}{2} = 73.5" },
          ],
          answer: "平均数\u224873.3，中位数=73.5",
          answerLatex: "\\bar{x} \\approx 73.3, \\ \\text{中位数}=73.5",
        },
        commonMistakes: [
          { mistake: "偶数个数据时中位数取第n/2个数", correction: "偶数时取中间两数的平均值。" },
          { mistake: "认为众数只有一个", correction: "可以有多个众数，也可以没有。" },
        ],
        summary: ["平均数=总和/n（被极端值影响）", "中位数=中间位（不受极端值影响）", "众数=最频繁值"],
        selfCheck: ["数据: 1,2,2,3,100。平均数和中位数分别是多少？哪个更典型？"],
      },
      {
        id: "stat-probability", chapterId: "statistics", title: "随机事件与概率",
        objectives: ["理解随机事件", "掌握古典概率公式", "能用树状图求概率"],
        motivation: "掷一颗公平骰子。出1的概率=1/6，因为6个面都一样。概率帮助我们在随机世界中做预测和决策。",
        intuition: "概率衡量事件发生的可能性：不会发生\u21920，一定发生\u21921，可能发生也可能不发生\u2192介于0和1之间。",
        definition: "古典概型：所有结果等可能。概率P(A)=事件A包含的结果数/总结果数。",
        formulaLatex: "P(A) = \\frac{m}{n}",
        formulaExplanation: "m是事件A的结果数，n是总结果数。前提：所有结果机会相等。",
        conditions: "只在古典概型中成立。概率取值范围0~1。",
        example: {
          problem: "从扑克牌中随机取一张，取到红桃的概率是多少？",
          steps: [
            { description: "总数n=52，红桃m=13", latex: "n=52, m=13" },
            { description: "P=13/52=1/4", latex: "P = \\frac{1}{4}" },
          ],
          answer: "1/4",
          answerLatex: "\\frac{1}{4}",
        },
        commonMistakes: [
          { mistake: "概率的分母用错", correction: "概率总是(关注结果数)/(总结果数)。" },
          { mistake: "把概率写成大于1", correction: "概率范围0~1。" },
        ],
        summary: ["概率=关注结果数/总结果数", "范围0~1", "0不可能，1必然"],
        selfCheck: ["掷两颗骰子，和为7的概率是多少？", "天气预报70%降水概率是什么意思？"],
      },
    ],
  },
  {
    id: "applications", number: 8, title: "综合应用与数学建模",
    description: "综合运用所学知识解决实际问题，建立数学模型，培养分析和解决问题的能力。",
    prerequisites: ["全部前七章内容"],
    teachingPoints: ["建模过程：理解问题\u2192建立关系\u2192求解\u2192解释\u2192验证", "不同类型问题对应不同数学模型"],
    commonMisconceptions: ["认为模型必须完美无缺", "把数学结果直接当实际问题答案"],
    discussionQuestions: ["你身边有哪些可以用方程或函数建模的实际问题？", "为什么数学模型的解不一定在现实中有意义？"],
    knowledgePoints: [
      {
        id: "app-model", chapterId: "applications", title: "方程与函数模型",
        objectives: ["能从实际情境中建立方程模型", "理解一次函数模型的参数含义", "能建立简单的二次函数模型"],
        motivation: "一家小工厂：每月固定成本3000元，每件产品材料成本20元。每月销售x件，总成本y=20x+3000。如果每件卖50元，什么时候盈利？需要解不等式——一个简单的数学模型。",
        intuition: "数学建模分为三步：翻译——把实际问题翻译成数学语言；求解——用数学工具解出答案；翻译回来——把数学答案翻译成实际的含义并验证。",
        definition: "模型：一个能代表真实世界情况的数学对象（方程、函数、图形等）。模型的建立需要识别变量、分析关系、确定参数和取值范围。",
        formulaLatex: "y = kx + b \\ \\text{（线性模型）} \\\\ y = ax^2 + bx + c \\ \\text{（二次模型）}",
        formulaExplanation: "线性模型适合匀速变化的量。二次模型适合加速变化的量（抛体运动、面积问题）。",
        conditions: "模型必须在取值范围内有效（如时间不能为负）。超出适用范围时模型失效。",
        example: {
          problem: "某公司：固定成本20000元，每件可变成本15元。售价40元，卖多少件开始盈利？",
          steps: [
            { description: "设销售x件；成本=20000+15x；收入=40x", latex: "40x > 20000 + 15x" },
            { description: "解不等式", latex: "25x > 20000" },
            { description: "最少销量", latex: "x > 800 \\Rightarrow 801 \\text{件}" },
          ],
          answer: "801件",
          answerLatex: "x > 800 \\Rightarrow 801 \\text{件}",
        },
        commonMistakes: [
          { mistake: "忘记考虑固定成本", correction: "成本=固定成本+可变成本。" },
          { mistake: "解出答案在实际中不适用", correction: "必须检验解是否合理，如件数应是整数。" },
        ],
        summary: ["模型=实际问题\u2192数学表达", "解数学\u2192检验实际意义", "模型有适用范围"],
        selfCheck: ["一辆出租车：起步价10元，每公里2元。写出总费用y与距离x的函数模型。"],
      },
      {
        id: "app-geometry-opt", chapterId: "applications", title: "几何最值与测量",
        objectives: ["能用几何方法解决最大值和最小值问题", "掌握间接测量方法"],
        motivation: "用50m长的铁丝围成一个矩形花园。如何围使得面积最大？通过二次函数模型配方法得x=12.5时面积最大。这就是几何最优化问题。",
        intuition: "几何最值问题的核心是识别约束条件（如铁丝长固定），然后用代数式表达面积/周长等目标量，用函数方法求最值。",
        definition: "几何最值问题：在一定条件下求面积、周长的最大值或最小值。常通过配方法或相似比公式求解。",
        formulaLatex: "S = x(\\frac{P}{2} - x) \\ \\xrightarrow{\\text{配方}} \\ \\text{求顶点}",
        formulaExplanation: "P是周长，x是一条边长。另一边由周长限制自然得到。写成二次函数后配方求顶点。",
        conditions: "变量的取值范围受几何意义限制（边长>0，面积>0）。",
        example: {
          problem: "用16米长的绳子围成矩形，最大面积是多少？",
          steps: [
            { description: "设一边为x，另一边为8-x", latex: "S = x(8-x) = -x^2 + 8x" },
            { description: "配方", latex: "S = -(x-4)^2 + 16" },
            { description: "x=4时最大=16m\u00B2", latex: "S_{\\max} = 16" },
          ],
          answer: "16m\u00B2（正方形）",
          answerLatex: "S_{\\max} = 16 \\text{ m}^2",
        },
        commonMistakes: [
          { mistake: "配方计算错误", correction: "配方法：-x\u00B2+8x=-(x\u00B2-8x+16-16)=-(x-4)\u00B2+16。" },
        ],
        summary: ["几何最值=建立二次函数\u2192配方求顶点", "配方法：提取系数\u2192完全平方\u2192求极值"],
        selfCheck: ["用20米长的绳子围成矩形，最大面积是多少？"],
      },
    ],
  },
];
