import type { Chapter } from "./types";

export const CHAPTERS: Chapter[] = [
  {
    id: "vectors",
    number: 1,
    title: "向量基础",
    description: "从几何直观出发，建立向量的概念，学习加减法、点积和线性组合，建立'用代数描述方向'的思维。",
    prerequisites: ["平面直角坐标系", "勾股定理", "三角函数初步"],
    teachingPoints: [
      "强调向量是有大小有方向的量，区别于标量",
      "用平行四边形法则和三角形法则建立加减法的几何直观",
      "点积与夹角的关系是连接代数和几何的关键",
    ],
    commonMisconceptions: [
      "混淆向量和点：向量表示方向和长度，点表示位置",
      "认为点积为零的向量一定垂直（只在实数范围内成立）",
      "混淆向量的夹角和两条直线的夹角",
    ],
    discussionQuestions: [
      "为什么向量的加法满足平行四边形法则？",
      "两个向量点积为负意味着什么？",
      "任一向量是否都可以表示为两个给定向量的线性组合？为什么有时可以，有时不行？",
    ],
    knowledgePoints: [
      {
        id: "vec-concept",
        chapterId: "vectors",
        title: "向量的概念与表示",
        slug: "vector-concept",
        objectives: ["能区分标量和向量", "会在平面中表示向量", "理解向量的两个要素：大小和方向"],
        motivation: "在地图上，光说'走500米'是不够的——朝哪个方向走？这就需要一个既有大小又有方向的量来描述。",
        intuition: "向量就像一个带箭头的指针：箭头的指向告诉我们方向，箭头的长度告诉我们距离。数学上，我们用一对坐标(x,y)来表示它——x告诉我们在水平方向走多远，y告诉我们在垂直方向走多远。",
        definition: "向量（vector）是既有大小又有方向的量。在二维平面中，向量表示为有序数对 (x, y)，其中 x 是水平分量，y 是垂直分量。标量（scalar）是只有大小的量，如温度、质量。",
        formulaLatex: "\\vec{v} = (v_x, v_y)",
        formulaExplanation: "vₓ 表示向量 v 在 x 轴上的投影长度，vᵧ 表示在 y 轴上的投影长度。",
        example: {
          problem: "从点 A(2, 3) 出发，到达点 B(5, 7)，请写出表示这次移动的向量。",
          steps: [
            { description: "向量的水平分量 = 终点x - 起点x", latex: "v_x = 5 - 2 = 3" },
            { description: "向量的垂直分量 = 终点y - 起点y", latex: "v_y = 7 - 3 = 4" },
            { description: "结果", latex: "\\vec{v} = (3, 4)" },
          ],
          answer: "(3, 4)",
          answerLatex: "\\vec{v} = (3, 4)",
        },
        commonMistakes: [
          { mistake: "认为(3,4)一定是在A点出发", correction: "向量(3,4)可以从任意起点出发，它只表示偏移量。" },
          { mistake: "混淆向量和点", correction: "点A(2,3)表示位置，向量(3,4)表示从任意位置出发的偏移。" },
        ],
        summary: ["向量 = 有大小 + 有方向", "二维向量写为 (x, y)", "向量与起点无关，可以平移到任何位置"],
        selfCheck: [
          "我能否举例说明生活中哪些是向量，哪些是标量？",
          "给定起点和终点，我能否正确写出对应的向量？",
          "我能否在坐标纸上画出给定的向量？",
        ],
      },
      {
        id: "vec-arithmetic",
        chapterId: "vectors",
        title: "向量加减法和数乘",
        slug: "vector-addition",
        objectives: ["掌握向量加法（分量相加）", "掌握向量减法的几何意义", "理解标量乘法的几何效果（拉伸/缩短/反向）"],
        motivation: "你划船渡河：船自身的速度是一个向量，水流的速度是另一个向量。船实际的运动轨迹是什么？你需要把这两个向量加在一起。",
        intuition: "向量加法就是'先走一段，再走一段'：把第二个向量的起点接到第一个向量的终点上（三角形法则），或者把它们放在同一个起点，画出平行四边形（平行四边形法则）。两种方法结果相同。",
        definition: "向量加法：对应分量分别相加。\n数乘：标量 k 乘以向量的每个分量。\nk>0 时方向不变、长度缩放；k<0 时方向反转。",
        formulaLatex: "\\vec{a} + \\vec{b} = (a_x + b_x, a_y + b_y) \\\\ k\\vec{v} = (kv_x, kv_y)",
        formulaExplanation: "加法就是分量对应相加。数乘就是每个分量都乘以同一个数。",
        example: {
          problem: "已知 a = (3, 1)，b = (-1, 2)，计算 (1) a + b，(2) 2a，(3) -b",
          steps: [
            { description: "a + b：x分量 3+(-1)=2，y分量 1+2=3", latex: "\\vec{a}+\\vec{b} = (2, 3)" },
            { description: "2a：每个分量乘2", latex: "2\\vec{a} = (6, 2)" },
            { description: "-b：每个分量乘-1（方向反转）", latex: "-\\vec{b} = (1, -2)" },
          ],
          answer: "(2, 3), (6, 2), (1, -2)",
          answerLatex: "\\vec{a}+\\vec{b}=(2,3), 2\\vec{a}=(6,2), -\\vec{b}=(1,-2)",
        },
        commonMistakes: [
          { mistake: "向量加减时两个分量交叉相加", correction: "加法是对应分量相加：(aₓ+bₓ, aᵧ+bᵧ)，不是 (aₓ+bᵧ, aᵧ+bₓ)。" },
          { mistake: "认为 kv 只改变长度不改变方向", correction: "当 k<0 时，方向反转（掉头）。" },
        ],
        summary: ["加法 = 分量对应相加，几何上是首尾相接或平行四边形", "减法 a-b = a + (-b)，几何上是从b的终点指向a的终点的向量", "数乘 k>0 拉伸，0<k<1 缩短，k<0 反向"],
        selfCheck: [
          "我能否用平行四边形法则在纸上画出 a + b？",
          "我能否用三角形法则解释 a - b？",
          "3v 和 v/3 几何上有何不同？",
        ],
      },
      {
        id: "vec-length",
        chapterId: "vectors",
        title: "长度、距离与单位向量",
        slug: "vector-norm",
        objectives: ["用勾股定理计算向量的长度（模）", "计算两点之间的距离", "求单位向量"],
        motivation: "地图上的'比例尺'是大家熟悉的：图上1cm代表实际1km。向量的'长度'（模）就是告诉我们从起点到终点有多远。",
        intuition: "向量 (3, 4) 可以用直角三角形的两条直角边来理解：水平走了3步，竖直走了4步。斜边的长度（也就是实际距离）是多少？勾股定理告诉我们：√(3²+4²) = 5。这就是向量的模。",
        definition: "向量 v = (x, y) 的模（长度）为 |v| = √(x² + y²)。单位向量是模为1的向量，v/|v| 就是与 v 同方向的单位向量。",
        formulaLatex: "|\\vec{v}| = \\sqrt{v_x^2 + v_y^2}, \\quad \\hat{v} = \\frac{\\vec{v}}{|\\vec{v}|}",
        formulaExplanation: "模的计算来自勾股定理。单位向量 = 原向量 ÷ 模（将长度缩放到1）。",
        example: {
          problem: "求向量 v = (6, 8) 的模和同方向的单位向量。",
          steps: [
            { description: "计算模：√(6² + 8²) = √(36 + 64)", latex: "|\\vec{v}| = \\sqrt{6^2+8^2} = \\sqrt{100} = 10" },
            { description: "单位向量 = v / 10", latex: "\\hat{v} = (\\frac{6}{10}, \\frac{8}{10}) = (0.6, 0.8)" },
            { description: "验证：0.6² + 0.8² = 0.36 + 0.64 = 1 ✓", latex: "|\\hat{v}| = 1" },
          ],
          answer: "模=10，单位向量(0.6, 0.8)",
          answerLatex: "|\\vec{v}|=10, \\hat{v}=(0.6, 0.8)",
        },
        commonMistakes: [
          { mistake: "忘记开平方根，用 x²+y² 直接当长度", correction: "|v| = √(x²+y²)，必须开根号。" },
          { mistake: "求单位向量时忘记除以模", correction: "单位向量 = v / |v|，需要对每个分量除以模。" },
        ],
        summary: ["模 |v| = √(x²+y²) = 勾股定理", "单位向量 = v / |v|（方向不变，长度为1）", "两点距离 = |终点 - 起点|"],
        selfCheck: [
          "我能否用勾股定理推导出求模的公式？",
          "如果一个向量长度是0，它的单位向量是什么？",
          "(3,4) 和 (6,8) 哪个更长？它们有什么区别？",
        ],
      },
      {
        id: "vec-dot",
        chapterId: "vectors",
        title: "点积、夹角和正交",
        slug: "vector-dot-product",
        objectives: ["计算两个向量的点积", "用点积求两向量夹角", "判断两个向量是否正交（垂直）"],
        motivation: "推箱子时，如果沿着箱子的运动方向用力，力就全部转化为运动；如果从侧面推，大部分力浪费了。'有效用力'是多少？这就是点积的概念。",
        intuition: "点积分两步：先把一个向量投影到另一个方向上，再看投影的长度乘以第二个向量的长度。公式上更简单——把对应分量相乘再相加。两个向量点积越大，说明它们方向越接近。",
        definition: "a·b = aₓbₓ + aᵧbᵧ = |a||b|cosθ。点积 = 0 时两向量垂直（正交）。cosθ = (a·b) / (|a||b|)。",
        formulaLatex: "\\vec{a}\\cdot\\vec{b} = a_x b_x + a_y b_y = |\\vec{a}||\\vec{b}|\\cos\\theta",
        formulaExplanation: "左式为分量计算法（最实用），右式为几何定义法（解释含义）。两者等价。",
        example: {
          problem: "已知 a = (2, 3)，b = (4, -1)，求 a·b 和两向量的夹角。",
          steps: [
            { description: "点积：2×4 + 3×(-1)", latex: "\\vec{a}\\cdot\\vec{b} = 8 - 3 = 5" },
            { description: "计算模：|a|=√(4+9)=√13≈3.61", latex: "|\\vec{a}| = \\sqrt{13}" },
            { description: "|b|=√(16+1)=√17≈4.12", latex: "|\\vec{b}| = \\sqrt{17}" },
            { description: "cosθ = 5/(√13×√17) ≈ 0.34", latex: "\\cos\\theta = \\frac{5}{\\sqrt{221}} \\approx 0.34" },
            { description: "θ ≈ arccos(0.34) ≈ 70°", latex: "\\theta \\approx 70^\\circ" },
          ],
          answer: "a·b=5, θ≈70°",
          answerLatex: "\\vec{a}\\cdot\\vec{b}=5, \\theta \\approx 70^\\circ",
        },
        commonMistakes: [
          { mistake: "忘记点积的计算公式是分量相乘再相加", correction: "a·b = aₓbₓ + aᵧbᵧ，不是 (aₓ+aᵧ)(bₓ+bᵧ)。" },
          { mistake: "用点积的绝对值判断正交", correction: "正交的条件是点积 = 0（精确的0），不是接近于0。" },
        ],
        summary: ["点积 = 分量乘积之和 = |a||b|cosθ", "点积>0 → 锐角；点积=0 → 正交（垂直）；点积<0 → 钝角", "夹角公式：cosθ = (a·b)/(|a||b|)"],
        selfCheck: ["我能否解释为什么 a·a = |a|²？", "点积为0的两个向量一定是垂直的吗？", "点积为负意味着什么几何关系？"],
      },
      {
        id: "vec-linear-combination",
        chapterId: "vectors",
        title: "线性组合及其几何意义",
        slug: "linear-combination",
        objectives: ["理解线性组合的定义", "用线性组合表示一个向量", "理解基向量的概念"],
        motivation: "如果向东走一步是 (1, 0)，向北走一步是 (0, 1)，那么'向东走3步再向北走4步'就是 3(1,0) + 4(0,1) = (3,4)。这是最基本的线性组合思想。",
        intuition: "线性组合就是用'数乘+加法'来表示新向量。可以想象两个基础方向（基向量）像编织的经纬线一样——通过调整每条线的长度（系数），可以覆盖整个平面上的任意一点。",
        definition: "给定向量 v₁, v₂, ..., vₙ 和标量 c₁, c₂, ..., cₙ，称 c₁v₁ + c₂v₂ + ... + cₙvₙ 为这些向量的线性组合。特别地，如果任意二维向量都能用 v₁, v₂ 的线性组合表示，则称 {v₁, v₂} 构成二维空间的一组基。",
        formulaLatex: "c_1 \\vec{v}_1 + c_2 \\vec{v}_2 + \\cdots + c_n \\vec{v}_n",
        formulaExplanation: "c₁, c₂, ... 是标量系数，控制每个向量参与多少。每个向量被缩放后相加。",
        example: {
          problem: "用 i = (1, 0) 和 j = (0, 1) 的线性组合表示 v = (5, -3)。",
          steps: [
            { description: "找到系数 c₁, c₂ 使 c₁(1,0) + c₂(0,1) = (5,-3)", latex: "(c_1, c_2) = (5, -3)" },
            { description: "所以", latex: "\\vec{v} = 5\\vec{i} + (-3)\\vec{j}" },
          ],
          answer: "v = 5i - 3j",
          answerLatex: "\\vec{v} = 5\\vec{i} - 3\\vec{j}",
        },
        commonMistakes: [
          { mistake: "认为任意三个二维向量都可以线性组合出所有二维向量", correction: "三个二维向量中必然有冗余，实际上两个不共线的向量就够了。" },
        ],
        summary: ["线性组合 = 各向量分别缩放后再相加", "i=(1,0) 和 j=(0,1) 是最基本的基向量", "用不同的基可以表示同一个向量，但系数不同"],
        selfCheck: ["给定两个不共线的二维向量，能否用它们表达平面上的任意向量？", "如果两个向量共线（方向相同或相反），它们的线性组合只能覆盖什么？"],
      },
    ],
  },
  {
    id: "matrices",
    number: 2,
    title: "矩阵基础",
    description: "学习矩阵作为'数字表格'和'线性变换的编码'两层含义，掌握基本运算。",
    prerequisites: ["向量基础", "向量数乘和加法", "点积"],
    teachingPoints: [
      "矩阵不仅是数字表格，更是线性变换的表示",
      "矩阵乘法的定义源于复合变换的需要",
      "矩阵乘法一般不可交换，这与数的乘法完全不同",
    ],
    commonMisconceptions: [
      "认为矩阵乘法就像对应元素相乘（那是 Hadamard 乘积，不是矩阵乘法）",
      "认为所有矩阵都有逆矩阵（只有方阵且行列式非零时才可逆）",
      "认为 AB = BA（矩阵乘法一般不交换）",
    ],
    discussionQuestions: [
      "为什么矩阵乘法的定义这么'奇怪'（不是对应元素相乘）？",
      "两个非零矩阵相乘可能得到零矩阵吗？",
      "什么样的矩阵没有逆矩阵？",
    ],
    knowledgePoints: [
      {
        id: "mat-concept",
        chapterId: "matrices",
        title: "矩阵的概念、形状和元素",
        slug: "matrix-concept",
        objectives: ["理解矩阵是有行有列的数字表格", "知道矩阵形状 m×n 的含义", "会读写矩阵元素 aᵢⱼ"],
        motivation: "班级里有40个学生，每人有语文、数学、英语三门成绩。如果一张一张地看成绩单很麻烦，但把它们排列成一个40行3列的表格，就能一目了然。这就是矩阵的基本用途：高效组织数据。",
        intuition: "矩阵就像Excel表格：每个数字坐在特定的'座位'上——第几排（行）第几列。这个座位编号（索引）帮助我们快速定位和操作数据。",
        definition: "矩阵是由 m×n 个数字按 m 行 n 列排列的矩形数组。aᵢⱼ 表示第 i 行第 j 列的元素。当 m=n 时称为方阵（square matrix）。",
        formulaLatex: "A = \\begin{pmatrix} a_{11} & a_{12} & \\cdots & a_{1n} \\\\ a_{21} & a_{22} & \\cdots & a_{2n} \\\\ \\vdots & \\vdots & \\ddots & \\vdots \\\\ a_{m1} & a_{m2} & \\cdots & a_{mn} \\end{pmatrix}",
        formulaExplanation: "m 是行数（Rows），n 是列数（Columns）。标准矩阵用大写字母表示。",
        example: {
          problem: "写出一个 2×3 矩阵，第一行是 1, 2, 3，第二行是 4, 5, 6。请问 a₂₃ 是多少？",
          steps: [
            { description: "写出矩阵", latex: "\\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\end{pmatrix}" },
            { description: "a₂₃ = 第2行第3列 = 6", latex: "a_{23} = 6" },
          ],
          answer: "a₂₃ = 6",
          answerLatex: "a_{23} = 6",
        },
        commonMistakes: [
          { mistake: "混淆行和列的顺序", correction: "aᵢⱼ 中 i 是行号（从上往下数），j 是列号（从左往右数）。" },
        ],
        summary: ["矩阵 = m行 × n列 的数字表格", "aᵢⱼ 表示第 i 行第 j 列的元素", "方阵 = 行数等于列数的矩阵"],
        selfCheck: ["我能否正确写出给定行列数的矩阵？", "给定 aᵢⱼ 的编号规则，我能否找到对应元素？"],
      },
      {
        id: "mat-operations",
        chapterId: "matrices",
        title: "矩阵加法、数乘与乘法",
        slug: "matrix-operations",
        objectives: ["掌握矩阵加法（同形矩阵对应元素相加）", "掌握矩阵数乘", "掌握矩阵乘法的规则"],
        motivation: "两边店铺的销售数据分别用矩阵 A 和 B 记录（行=商品，列=月份）。想合并两家店的数据，只需 A+B（对应位置相加）。想知道统一的涨价幅度（比如全部涨1.5倍），只需 1.5×A。",
        intuition: "矩阵加法最简单——同位置的数字相加。矩阵乘法最特别：它不是对应位置相乘，而是'行×列'——左边矩阵的每一行，分别和右边矩阵的每一列做点积。这一设计是为了让矩阵能表示'复合变换'（后面会讲）。",
        definition: "同形矩阵加法：对应元素相加。数乘：每个元素乘 k。乘法：A(m×n) × B(n×p) = C(m×p)，其中 cᵢⱼ = A第i行 · B第j列（点积）。",
        formulaLatex: "(A+B)_{ij} = a_{ij} + b_{ij} \\\\ (kA)_{ij} = k \\cdot a_{ij} \\\\ (AB)_{ij} = \\sum_{k=1}^{n} a_{ik} b_{kj}",
        formulaExplanation: "乘法要求 A 的列数 = B 的行数。结果矩阵第 i 行第 j 列 = A的第i行 与 B的第j列 中对应元素乘积之和。",
        example: {
          problem: "计算 ┌1 2┐ × ┌5 6┐\n      └3 4┘   └7 8┘",
          steps: [
            { description: "结果(1,1) = 第1行·第1列", latex: "1\\times5 + 2\\times7 = 5 + 14 = 19" },
            { description: "结果(1,2) = 第1行·第2列", latex: "1\\times6 + 2\\times8 = 6 + 16 = 22" },
            { description: "结果(2,1) = 第2行·第1列", latex: "3\\times5 + 4\\times7 = 15 + 28 = 43" },
            { description: "结果(2,2) = 第2行·第2列", latex: "3\\times6 + 4\\times8 = 18 + 32 = 50" },
            { description: "最终结果", latex: "\\begin{pmatrix} 19 & 22 \\\\ 43 & 50 \\end{pmatrix}" },
          ],
          answer: "┌19 22┐\n└43 50┘",
          answerLatex: "\\begin{pmatrix} 19 & 22 \\\\ 43 & 50 \\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "把矩阵乘法当做对应元素相乘", correction: "矩阵乘法 ≠ 对应元素相乘。正确方式：左边第 i 行 × 右边第 j 列 = 结果第 i 行第 j 列。" },
          { mistake: "形状不匹配的矩阵也尝试相乘", correction: "只有 A 的列数 = B 的行数时 AB 才有定义。" },
        ],
        summary: ["加法 = 对应元素相加（必须同形）", "数乘 = 每个元素 × k", "乘法 = 行×列点积（不是对应元素相乘）"],
        selfCheck: ["我能否说出两个 3×2 的矩阵能否相乘？结果是什么形状？", "矩阵加法和乘法分别要求什么条件？"],
      },
      {
        id: "mat-transpose-inverse",
        chapterId: "matrices",
        title: "转置矩阵、单位矩阵与逆矩阵",
        slug: "matrix-transpose-inverse",
        objectives: ["理解转置（行列互换）", "认识单位矩阵 I", "理解逆矩阵 A⁻¹ 的概念和求法"],
        motivation: "转置就像是把矩阵'翻个面'——行变列、列变行。单位矩阵 I 是矩阵中的'1'：任何矩阵乘以 I 都不变。逆矩阵 A⁻¹ 是 A 的'倒数'：A × A⁻¹ = I。",
        intuition: "如果矩阵代表一个变换（旋转、拉伸...），那么它的逆矩阵就是'撤销'这个变换：先旋转再逆向旋转，回到了原点。单位矩阵 I 就是'什么都不做'的变换。",
        definition: "转置 Aᵀ：行变列、列变行。单位矩阵 I：对角线全1、其余全0。逆矩阵 A⁻¹：满足 AA⁻¹ = A⁻¹A = I。（仅方阵且行列式≠0时存在）",
        formulaLatex: "(A^T)_{ij} = A_{ji} \\\\ I_n = \\begin{pmatrix} 1 & 0 & \\cdots & 0 \\\\ 0 & 1 & \\cdots & 0 \\\\ \\vdots & \\vdots & \\ddots & \\vdots \\\\ 0 & 0 & \\cdots & 1 \\end{pmatrix} \\\\ A A^{-1} = A^{-1}A = I",
        formulaExplanation: "转置就是把行和列对调。单位矩阵对角线上是1其余是0。2×2逆矩阵公式：A⁻¹ = (1/det) × ┌d -b: -c a┐。",
        example: {
          problem: "求 A = ┌2 1┐ 的逆矩阵。\n       └1 2┘",
          steps: [
            { description: "计算行列式", latex: "\\det(A) = 2\\times2 - 1\\times1 = 3 \\neq 0" },
            { description: "2×2逆矩阵公式", latex: "A^{-1} = \\frac{1}{3}\\begin{pmatrix} 2 & -1 \\\\ -1 & 2 \\end{pmatrix}" },
            { description: "验证", latex: "A A^{-1} = \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix} = I" },
          ],
          answer: "┌2/3 -1/3┐\n└-1/3 2/3┘",
          answerLatex: "A^{-1} = \\frac{1}{3}\\begin{pmatrix} 2 & -1 \\\\ -1 & 2 \\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "认为非方阵也有逆矩阵", correction: "只有方阵（行列数相等）才可能有逆矩阵。" },
          { mistake: "求逆矩阵时忘记除以行列式", correction: "2×2 的逆矩阵 = 1/det × ┌ d  -b : -c  a ┐，必须除以 det。" },
        ],
        summary: ["Aᵀ = 行变列、列变行", "I 是'什么都不做'的单位矩阵", "A⁻¹ 是 A 的'逆向操作'", "AA⁻¹ = A⁻¹A = I"],
        selfCheck: ["我能否写出 3×3 的单位矩阵？", "如果 det(A)=0，为什么 A 不可逆？"],
      },
      {
        id: "mat-commute",
        chapterId: "matrices",
        title: "矩阵乘法为什么不能随意交换",
        slug: "matrix-commutativity",
        objectives: ["理解 AB ≠ BA 一般情况", "理解矩阵乘法与函数复合的类比", "知道什么样的情况下 AB = BA"],
        motivation: "先穿袜子再穿鞋，和先穿鞋再穿袜子，结果完全不同。大多数'操作'的顺序是不能随便换的——矩阵乘法也是如此。",
        intuition: "矩阵乘法代表'复合变换'：AB 表示先做 B 的变换，再做 A 的变换。顺序不同，结果自然不同。就像先旋转再平移，和先平移再旋转，到达的位置完全不同。",
        definition: "矩阵乘法不满足交换律：普遍情况下 AB ≠ BA。只有在特殊情况下（如对角矩阵相乘、一个矩阵是单位矩阵等）才可能 AB = BA。这不是缺陷，正是因为矩阵代表变换，而变换的先后顺序会影响结果。",
        formulaLatex: "AB \\neq BA \\quad \\text{（一般情况下）}",
        formulaExplanation: "即使 AB 和 BA 都有定义（如两个 n×n 方阵），它们的结果通常也不同。",
        example: {
          problem: "A=┌0 1┐ B=┌1 0┐ 计算 AB 和 BA，比较它们是否相等。\n    └0 0┘   └0 0┘",
          steps: [
            { description: "AB = ┌0×1+1×0  0×0+1×0┐", latex: "AB = \\begin{pmatrix} 0 & 0 \\\\ 0 & 0 \\end{pmatrix}" },
            { description: "BA = ┌1×0+0×0  1×1+0×0┐", latex: "BA = \\begin{pmatrix} 0 & 1 \\\\ 0 & 0 \\end{pmatrix}" },
            { description: "AB ≠ BA", latex: "\\begin{pmatrix} 0 & 0 \\\\ 0 & 0 \\end{pmatrix} \\neq \\begin{pmatrix} 0 & 1 \\\\ 0 & 0 \\end{pmatrix}" },
          ],
          answer: "AB ≠ BA",
          answerLatex: "AB = \\mathbf{0}, BA \\neq \\mathbf{0}，不相等",
        },
        commonMistakes: [
          { mistake: "想当然地认为 AB = BA", correction: "矩阵乘法基本不能交换，把它想象成'先操作后操作'的顺序问题。" },
        ],
        summary: ["AB ≠ BA 是常态，不是例外", "交换成立的情况很少（I、对角矩阵等特殊情况）", "这与函数复合 f(g(x)) ≠ g(f(x)) 类似"],
        selfCheck: ["我能否举出两个 AB = BA 的例子？", "如果 A 和 B 都是对角矩阵，AB = BA 吗？"],
      },
      {
        id: "mat-data-transform",
        chapterId: "matrices",
        title: "用矩阵表示数据与变换",
        slug: "matrix-data-transform",
        objectives: ["理解矩阵的两面性：数据容器 vs 变换工具", "会用矩阵表示简单的坐标系变换", "理解矩阵乘向量 = 变换点"],
        motivation: "一张图片在 Photoshop 里旋转、缩放、变形——所有这些操作都可以用一个矩阵（变换）乘以矩阵（像素数据）来完成。这就是矩阵为什么是计算机图形学的核心。",
        intuition: "把矩阵想象成一张'规则说明书'。当它乘以一个向量时，就按照说明书的规定，把向量移到新位置。矩阵的各列正是'新的基向量'——原来 (1,0) 变成了第一列，(0,1) 变成了第二列。",
        definition: "以变换的视角看，一个 2×2 矩阵 M 的每一列分别表示变换后的 x 轴基向量和 y 轴基向量。应用变换到向量 v 上，就是 M·v。应用变换到所有点上，整个图形就被变换了。",
        formulaLatex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} \\begin{pmatrix} x \\\\ y \\end{pmatrix} = \\begin{pmatrix} ax + by \\\\ cx + dy \\end{pmatrix}",
        formulaExplanation: "新 x 坐标 = a·旧x + b·旧y；新 y 坐标 = c·旧x + d·旧y。矩阵的列向量就是变换后的基向量。",
        example: {
          problem: "如果变换矩阵 M = ┌2 0┐，它对向量 (3, 4) 做了什么？\n                       └0 3┘",
          steps: [
            { description: "M·(3,4) = (2×3+0×4, 0×3+3×4)", latex: "M\\begin{pmatrix}3\\\\4\\end{pmatrix} = \\begin{pmatrix}6\\\\12\\end{pmatrix}" },
            { description: "x坐标变为原来2倍，y坐标变为原来3倍", latex: "\\text{非均匀缩放：x方向×2，y方向×3}" },
          ],
          answer: "非均匀缩放：x变2倍，y变3倍",
          answerLatex: "M\\begin{pmatrix}x\\\\y\\end{pmatrix} = \\begin{pmatrix}2x\\\\3y\\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "认为矩阵第一行是变换后的x轴基向量", correction: "矩阵的列（不是行）对应变换后的基向量。第一列是(i→)，第二列是(j→)。" },
        ],
        summary: ["矩阵 = 数据表格 + 变换规则", "变换矩阵的列 = 变换后的基向量", "M·v = 将变换应用于向量 v"],
        selfCheck: ["写出将向量在 x 方向拉伸 2 倍、y 方向拉伸 3 倍的变换矩阵。", "如果变换矩阵是 ┌0 1:-1 0┐，它对向量 (1,0) 做了什么？"],
      },
    ],
  },
  {
    id: "linear-systems",
    number: 3,
    title: "线性方程组",
    description: "学习如何用矩阵语言描述方程组，掌握高斯消元法的系统性求解方法。",
    prerequisites: ["矩阵乘法", "矩阵的秩", "逆矩阵"],
    teachingPoints: [
      "每个线性方程组都能写成矩阵形式 Ax = b",
      "高斯消元 = 系统化地消除变量",
      "解的存在性和数量取决于矩阵的秩",
    ],
    commonMisconceptions: [
      "认为所有线性方程组都有解",
      "认为 n 个未知数 n 个方程一定有唯一解",
      "对自由变量的理解停留在'多出来的未知数'",
    ],
    discussionQuestions: [
      "如果增广矩阵出现了 [0 0 | 3] 这样的行，意味着什么？",
      "如何在不求解的情况下判断方程组有几个解？",
    ],
    knowledgePoints: [
      {
        id: "ls-matrix-form",
        chapterId: "linear-systems",
        title: "方程组的矩阵表示",
        slug: "linear-system-matrix",
        objectives: ["将方程组写成 Ax = b 的形式", "构造增广矩阵", "理解系数矩阵与常数项"],
        motivation: "面对一个5元方程组，写出5个方程再做消元会非常混乱。矩阵形式 Ax = b 把所有的系数打包成一个表格，求解变得系统化、程序化。",
        intuition: "把方程组想象成一台机器：输入一个向量 x，经过矩阵 A 的处理，输出向量 b。解方程就是反过来：给定输出 b，找到输入 x。",
        definition: "对于方程组 {a₁₁x₁ + a₁₂x₂ + ... = b₁; ..., 可以写成矩阵形式 Ax = b。其中 A 是系数矩阵，x 是未知数向量，b 是常数向量。将 A 和 b 合并写在一起就是增广矩阵。",
        formulaLatex: "A\\mathbf{x} = \\mathbf{b}, \\quad [A | \\mathbf{b}]",
        formulaExplanation: "增广矩阵把系数和常数放在一起，方便同时操作。",
        example: {
          problem: "把方程组 {2x+y=5, x-3y=-1} 写成矩阵形式和增广矩阵。",
          steps: [
            { description: "系数矩阵 A，未知数 x，常数 b", latex: "A = \\begin{pmatrix} 2 & 1 \\\\ 1 & -3 \\end{pmatrix}" },
            { description: "矩阵形式", latex: "\\begin{pmatrix} 2 & 1 \\\\ 1 & -3 \\end{pmatrix} \\begin{pmatrix} x \\\\ y \\end{pmatrix} = \\begin{pmatrix} 5 \\\\ -1 \\end{pmatrix}" },
            { description: "增广矩阵", latex: "\\left[\\begin{array}{cc|c} 2 & 1 & 5 \\\\ 1 & -3 & -1 \\end{array}\\right]" },
          ],
          answer: "Ax=b, 增广矩阵 [A|b]",
          answerLatex: "[A|\\mathbf{b}] = \\left[\\begin{array}{cc|c} 2 & 1 & 5 \\\\ 1 & -3 & -1 \\end{array}\\right]",
        },
        commonMistakes: [
          { mistake: "方程中缺少某变量时矩阵里忘了写0", correction: "例如 x+z=0 中缺少 y，系数矩阵中 y 的系数是 0，不能省略。" },
        ],
        summary: ["Ax = b：三合一（系数 × 未知数 = 常数）", "增广矩阵 = [A | b]", "每个方程对应系数矩阵的一行"],
        selfCheck: ["把 3x+2y-z=4, x-y+2z=1, 2x+y+z=3 写成增广矩阵。"],
      },
      {
        id: "ls-gauss",
        chapterId: "linear-systems",
        title: "高斯消元法",
        slug: "gauss-elimination",
        objectives: ["理解初等行变换（交换、倍乘、倍加）", "执行高斯消元过程", "将增广矩阵化为行阶梯形"],
        motivation: "高斯消元法是'加减消元法'的升级版——把手动瞎试变成系统算法，连计算机也能照着做。",
        intuition: "消元的每一步都是三种合法操作之一：(1) 交换两行（无所谓），(2) 某行乘以非零常数（等式两边同乘），(3) 某行加上另一行的倍数（一个方程加到另一个上）。这些操作不会改变解。目标是把矩阵化成'阶梯形'——每个'台阶'只对应一个变量。",
        definition: "高斯消元法通过三种初等行变换将增广矩阵化为行阶梯形（Row Echelon Form），然后用回代法求出解。初等行变换：(1)Rᵢ↔Rⱼ 交换，(2)Rᵢ←kRᵢ 倍乘，(3)Rᵢ←Rᵢ+kRⱼ 倍加。",
        formulaLatex: "\\text{初等行变换: } R_i \\leftrightarrow R_j, R_i \\leftarrow kR_i, R_i \\leftarrow R_i + kR_j",
        formulaExplanation: "三种操作分别表示交换行、倍乘行、行与行的线性组合。它们不改变方程组的解。",
        example: {
          problem: "用高斯消元法解方程组：x+2y=5, 3x-y=1",
          steps: [
            { description: "写增广矩阵", latex: "\\left[\\begin{array}{cc|c} 1 & 2 & 5 \\\\ 3 & -1 & 1 \\end{array}\\right]" },
            { description: "R2←R2-3R1（消去第2行x）", latex: "\\left[\\begin{array}{cc|c} 1 & 2 & 5 \\\\ 0 & -7 & -14 \\end{array}\\right]" },
            { description: "R2←R2÷(-7)", latex: "\\left[\\begin{array}{cc|c} 1 & 2 & 5 \\\\ 0 & 1 & 2 \\end{array}\\right]" },
            { description: "R1←R1-2R2（消去第1行y）", latex: "\\left[\\begin{array}{cc|c} 1 & 0 & 1 \\\\ 0 & 1 & 2 \\end{array}\\right]" },
            { description: "读解：x=1, y=2", latex: "x = 1, y = 2" },
          ],
          answer: "x=1, y=2",
          answerLatex: "x = 1, y = 2",
        },
        commonMistakes: [
          { mistake: "只对系数部分做行变换，忘记了常数项", correction: "增广矩阵中常数列必须和系数一起变换。" },
          { mistake: "做 Rᵢ←Rᵢ+kRⱼ 时，对 k 取错符号", correction: "为消去某元素，k = -(待消元素)/(主元)。" },
        ],
        summary: ["三种初等行变换不改变解", "正向消元：从左上往右下逐个消除", "回代：从下往上依次求值"],
        selfCheck: ["我能否用高斯消元法自己解一个 3×3 系统？", "为什么初等行变换不改变方程组的解？"],
      },
      {
        id: "ls-row-echelon",
        chapterId: "linear-systems",
        title: "行阶梯形矩阵",
        slug: "row-echelon-form",
        objectives: ["识别行阶梯形（REF）和简化行阶梯形（RREF）", "理解主元的概念", "从 REF 中读取矩阵的秩"],
        motivation: "行阶梯形就像是把矩阵'整理'到最简形式——所有前面浪费的多余信息被清除，矩阵的本质结构（秩、解的数量）一目了然。",
        intuition: "想象一个楼梯：每一层台阶都比上一层靠右。行阶梯形的每一行第一个非零元素（主元，pivot）就像楼梯的台阶——从上往下，一层比一层靠右。简化行阶梯形（RREF）更进一步：每个台阶不仅靠右，台阶本身还正好是1，且上面和下面全是0。",
        definition: "行阶梯形（REF）：(1) 全零行在最下方；(2) 每行第一个非零元素（主元）的列号严格递增。简化行阶梯形（RREF）额外：(3) 每个主元=1；(4) 主元所在列其他元素全为0。矩阵的秩 = 非零行数 = 主元个数。",
        formulaLatex: "\\operatorname{rank}(A) = \\text{非零行数} = \\text{主元个数}",
        formulaExplanation: "秩衡量矩阵中有多少个'独立'的信息行。",
        example: {
          problem: "判断下面矩阵是否行阶梯形：\n┌1 2 3┐\n└0 0 1┘",
          steps: [
            { description: "第1行主元在第1列（=1）", latex: "pivot_1 = a_{11}" },
            { description: "第2行主元在第3列（=1），第3列>第1列 ✓", latex: "pivot_2 = a_{23}" },
            { description: "是行阶梯形", latex: "\\text{REF: 主元列号递增}" },
          ],
          answer: "是行阶梯形，秩=2",
          answerLatex: "\\text{REF}, \\operatorname{rank}=2",
        },
        commonMistakes: [
          { mistake: "认为行阶梯形每行必须有1", correction: "REF 不要求主元是1，只要求'台阶'从左往右递增。" },
        ],
        summary: ["REF = 阶梯状：每行先非零比上一行靠右", "RREF = REF + 主元为1 + 所在列清0", "秩 = 非零行数"],
        selfCheck: ["我能否把一个普通矩阵手动转化为行阶梯形？", "主元个数为什么等于矩阵的秩？"],
      },
      {
        id: "ls-solution-types",
        chapterId: "linear-systems",
        title: "唯一解、无解和无穷多解",
        slug: "solution-types",
        objectives: ["根据秩和变量数判断解的情况", "区分三种解的类型", "理解解集的几何意义"],
        motivation: "为什么有些问题只有一个答案，有些根本没有，有些有无数个？了解'什么时候有解'比'怎么解'更有价值。",
        intuition: "解的情况取决于两个数：(1) 系数矩阵的秩 rank(A) = 有多少个'有效方程'；(2) 未知数个数 n = 有多少个自由度。秩 < 未知数 -> 有冗余自由度 -> 无穷多解。如果增广矩阵的秩 > 系数矩阵的秩 -> 矛盾 -> 无解。两者相等 -> 唯一解。",
        definition: "对于 Ax=b，设 r=rank(A)，r̂=rank([A|b])，n=未知数个数：\n(1) r̂>r → 无解（矛盾方程）；\n(2) r̂=r=n → 唯一解；\n(3) r̂=r<n → 无穷多解（n-r 个自由变量）。",
        formulaLatex: "\\begin{aligned} \\operatorname{rank}([A|b]) &> \\operatorname{rank}(A) &&\\Rightarrow \\text{无解} \\\\ \\operatorname{rank}([A|b]) &= \\operatorname{rank}(A) = n &&\\Rightarrow \\text{唯一解} \\\\ \\operatorname{rank}([A|b]) &= \\operatorname{rank}(A) < n &&\\Rightarrow \\text{无穷多解} \\end{aligned}",
        formulaExplanation: "n 是未知数个数。自由变量个数 = n - rank(A)。",
        example: {
          problem: "方程组 {x+y=2, 2x+2y=5} 有多少解？",
          steps: [
            { description: "增广矩阵", latex: "\\left[\\begin{array}{cc|c} 1 & 1 & 2 \\\\ 2 & 2 & 5 \\end{array}\\right]" },
            { description: "R2←R2-2R1", latex: "\\left[\\begin{array}{cc|c} 1 & 1 & 2 \\\\ 0 & 0 & 1 \\end{array}\\right]" },
            { description: "出现 0=1，矛盾", latex: "0 = 1 \\text{ 不可能} \\Rightarrow \\text{无解}" },
          ],
          answer: "无解",
          answerLatex: "\\text{无解（两条平行线不相交）}",
        },
        commonMistakes: [
          { mistake: "看到 [0 0 | 0] 行就认为无解", correction: "[0 0 | 0] 只是冗余方程，可以去掉。无解是 [0 0 | k] 且 k≠0。" },
        ],
        summary: ["r̂ > r → 无解", "r̂ = r = n → 唯一解", "r̂ = r < n → 无穷多解（有自由变量）"],
        selfCheck: ["写出一个有无穷多解的 2×3 方程组。", "如果系数矩阵满秩但增广矩阵再多一个矛盾行，解的情况如何？"],
      },
      {
        id: "ls-geometry",
        chapterId: "linear-systems",
        title: "解集的几何意义",
        slug: "solution-geometry",
        objectives: ["理解二元方程 = 直线", "理解三元方程 = 平面", "可视化解集的几何形态"],
        motivation: "2x+y=5 不只是代数式子——它本身就是平面上的一条直线！方程组解的存在性和数量，对应着直线（或平面）相交的方式。",
        intuition: "二元一次方程 = 二维平面上的一条直线。两个方程 → 两条直线相交 → 交点就是解。两线交一点 = 唯一解；两线平行不重合 = 无解；两线重合 = 无穷多解。这就是全部几何意义。",
        definition: "在二维空间中，每个线性方程 ax+by=c 代表一条直线。方程组的解是这些直线的交点。在三维空间中，每个方程代表一个平面，解是平面的交点（点、线或面）。",
        formulaLatex: "ax + by = c \\quad \\text{（平面直线）} \\\\ a_1x + a_2y + a_3z = b \\quad \\text{（空间平面）}",
        formulaExplanation: "每个项对应空间的维度。ax+by=c 中的系数 (a,b) 是直线（平面）的法向量。",
        example: {
          problem: "方程组 {x+y=3, 2x+2y=6} 在几何上代表什么？",
          steps: [
            { description: "第一个方程", latex: "y = -x + 3" },
            { description: "第二个方程 ÷2", latex: "y = -x + 3" },
            { description: "两方程等价 -> 同一条直线", latex: "\\text{两条方程描述同一条直线}" },
            { description: "直线上任意点都是解", latex: "\\text{无穷多解（直线上所有点）}" },
          ],
          answer: "两方程表示同一条直线，直线上所有点都是解",
          answerLatex: "\\text{两条方程表示同一条直线，无穷多解}",
        },
        commonMistakes: [
          { mistake: "混淆'直线解的个数'和'线段上的点的个数'", correction: "所有点（不限于整数）沿着直线都是解，因此有无穷多个。" },
        ],
        summary: ["每个方程 = 超平面（2D是直线，3D是平面）", "解 = 所有超平面的交集", "一条直线/一个平面 on its own gives infinite solutions"],
        selfCheck: ["说出三元一次方程组 x+y+z=1, x+y+z=2 在三维空间中的几何解释。"],
      },
    ],
  },
  {
    id: "linear-transforms",
    number: 4,
    title: "线性变换",
    description: "从几何视角理解矩阵——每个矩阵都代表空间的一种线性变换。",
    prerequisites: ["矩阵乘法", "向量加减法", "基向量的概念"],
    teachingPoints: [
      "线性变换保持网格平行且均匀",
      "变换后矩形的面积放大倍数 = 行列式",
      "复合变换 = 矩阵乘法 AB（先 B 后 A）",
    ],
    commonMisconceptions: [
      "认为变换只是移动图形（线性变换不是平移）",
      "认为变换矩阵的每一行（而不是列）是变换后的基向量",
      "认为复合变换 AB 是先 A 后 B（实际上是先 B 后 A）",
    ],
    discussionQuestions: [
      "什么样的变换不是线性的？",
      "为什么线性变换不能表示平移？",
    ],
    knowledgePoints: [
      {
        id: "lt-intuition",
        chapterId: "linear-transforms",
        title: "线性变换的直觉",
        slug: "transform-intuition",
        objectives: ["理解线性变换的三要素：不弯曲直线、保持原点、保持比例", "用基向量的变化理解变换", "区分线性变换和非线性变换"],
        motivation: "看一张照片被拉伸、被旋转、被斜切——这些操作有一个共同点：原来平行的线条，变换后仍然平行；原来等距的网格，变换后仍是等距的（虽然间距可能变了）。这就是线性变换。",
        intuition: "在空间中画一个均匀的方格网。对格子做线性变换后，网格线仍然是直的，仍然平行，间距仍然是均匀的——只是方向可能变了、间距可能被拉伸或压缩了。非线性变换会弯曲网格线（就像在照片上用手指划一下）。",
        definition: "线性变换 T 满足：(1) T(u+v) = T(u)+T(v)（保持加法结构）；(2) T(kv) = kT(v)（保持标量乘法）。几何上意味着：直线保持直线、原点不变、网格线保持平行且均匀分布。",
        formulaLatex: "T(\\vec{v}) = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} \\begin{pmatrix} x \\\\ y \\end{pmatrix}",
        formulaExplanation: "任何二维线性变换都可以用一个 2×2 矩阵表示。矩阵的列向量就是变换后的基向量 i 和 j。",
        example: {
          problem: "判断 T(x, y) = (x+2, y) 是否是线性变换。",
          steps: [
            { description: "检查原点：T(0,0) = (2, 0) ≠ (0, 0)", latex: "T(0, 0) = (2, 0) \\neq (0, 0)" },
            { description: "线性变换必须保持原点不变", latex: "\\text{这是平移，不是线性变换}" },
          ],
          answer: "不是线性变换（是平移）",
          answerLatex: "\\text{平移不是线性变换（不过原点）}",
        },
        commonMistakes: [
          { mistake: "认为平移是线性变换", correction: "线性变换必须保持原点不变。平移可以用 3×3 齐次坐标矩阵表示。" },
        ],
        summary: ["线性变换 = 不弯曲 + 不过原点移开 + 比例一致", "完全由变换后的基向量决定", "每个 2×2 矩阵是一种线性变换"],
        selfCheck: ["我能画出 ┌2 0:0 1┐ 把单位正方形变成什么形状吗？", "为什么缩放、旋转是线性的但平移不是？"],
      },
      {
        id: "lt-types",
        chapterId: "linear-transforms",
        title: "旋转、缩放、剪切和镜像",
        slug: "transform-types",
        objectives: ["识别和理解四种基本线性变换", "写出对应的变换矩阵", "在坐标平面上画出变换效果"],
        motivation: "所有线性变换都可以分解为四种基本操作的组合：旋转、缩放、剪切（错切）和镜像（反射）。理解了这四种，就理解了所有线性变换。",
        intuition: "旋转：把网格整体绕原点转动一个角度 θ。缩放：把网格在某个方向上拉长或缩短。剪切：把网格\u201C推歪\u201D——矩形变成平行四边形，但面积不变。镜像：把网格翻转到轴的另一侧。",
        definition: "旋转 θ 角的矩阵 = [[cosθ, -sinθ], [sinθ, cosθ]]；缩放 = [[sx, 0], [0, sy]]；水平剪切 = [[1, k], [0, 1]]；镜像关于x轴 = [[1, 0], [0, -1]]。",
        formulaLatex: "R_\\theta = \\begin{pmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{pmatrix}, \\quad S = \\begin{pmatrix} s_x & 0 \\\\ 0 & s_y \\end{pmatrix}, \\quad H = \\begin{pmatrix} 1 & k \\\\ 0 & 1 \\end{pmatrix}",
        formulaExplanation: "旋转矩阵中，cosθ 和 sinθ 来自单位圆。剪切矩阵中 k 控制倾斜程度。",
        example: {
          problem: "写出逆时针旋转 90° 的变换矩阵，并验证它将向量 (1, 0) 变为 (0, 1)。",
          steps: [
            { description: "cos 90°=0, sin 90°=1", latex: "R_{90} = \\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix}" },
            { description: "变换 (1,0)", latex: "\\begin{pmatrix}0\\\\1\\end{pmatrix} = \\begin{pmatrix}0 & -1\\\\1 & 0\\end{pmatrix}\\begin{pmatrix}1\\\\0\\end{pmatrix}" },
          ],
          answer: "R₉₀ = [0,-1; 1,0]",
          answerLatex: "R_{90^\\circ} = \\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "旋转矩阵中 sin 的符号弄反", correction: "逆时针旋转用 [cos -sin; sin cos]。顺时针则 sin 的符号上下对调。" },
        ],
        summary: ["旋转：Rθ = [[cosθ -sinθ], [sinθ cosθ]]", "缩放：diag(sx, sy)", "剪切：[[1 k],[0 1]] 或 [[1 0],[k 1]]", "镜像：对角线上的 ±1"],
        selfCheck: ["我能写出按 x 轴镜像的矩阵吗？", "先旋转 90° 再按 x 轴镜像的矩阵是什么？"],
      },
      {
        id: "lt-compose",
        chapterId: "linear-transforms",
        title: "变换矩阵与复合变换",
        slug: "transform-composition",
        objectives: ["理解复合变换 = 矩阵乘法", "知道复合顺序从右向左", "将复杂变换分解为基本变换的复合"],
        motivation: "在游戏引擎中，一个3D角色可能同时被缩放、旋转和平移。组合这些操作不是分别独立进行计算，而是把它们乘成一个大矩阵，计算一次完事。",
        intuition: "先旋转再缩放 = (缩放矩阵) × (旋转矩阵)。注意：右边的变换先发生！这就像函数复合 f(g(x))——g 先算，f 后算。矩阵乘法继承了这个'从右向左执行'的顺序。",
        definition: "复合变换 = 矩阵乘法。如果 T(x) = A(Bx)，则 T 的矩阵 = AB。注意：B 先作用于 x，然后 A 作用于结果。矩阵乘法从右向左对应变换的先后顺序。",
        formulaLatex: "T_1 \\circ T_2 \\text{ 的矩阵 } = A_1 A_2 \\quad \\text{（}T_2\\text{先执行）}",
        formulaExplanation: "先 T₂ 后 T₁ ≡ 先乘 A₂ 再乘 A₁ ≡ 矩阵 A₁A₂。",
        example: {
          problem: "先旋转 90°再水平拉伸 2 倍的变换矩阵是什么？",
          steps: [
            { description: "旋转90°矩阵", latex: "R = \\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix}" },
            { description: "拉伸矩阵", latex: "S = \\begin{pmatrix} 2 & 0 \\\\ 0 & 1 \\end{pmatrix}" },
            { description: "复合 = S×R（R先执行）", latex: "SR = \\begin{pmatrix} 2 & 0 \\\\ 0 & 1 \\end{pmatrix} \\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix} = \\begin{pmatrix} 0 & -2 \\\\ 1 & 0 \\end{pmatrix}" },
          ],
          answer: "┌0 -2┐\n└1  0┘",
          answerLatex: "\\begin{pmatrix} 0 & -2 \\\\ 1 & 0 \\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "认为 AB 表示先A后B", correction: "AB 应用于 x：ABx = A(Bx)，B 先作用。矩阵乘法从右向左执行。" },
          { mistake: "交换复合变换的顺序期望相同结果", correction: "旋转再缩放 ≠ 缩放再旋转。顺序很重要！" },
        ],
        summary: ["复合变换 = 矩阵乘积", "右边矩阵先执行（先右后左）", "基本变换可以通过乘法组合成复杂变换"],
        selfCheck: ["为什么先缩放再旋转和先旋转再缩放的结果不同？", "RS 和 SR 在什么情况下相等？"],
      },
      {
        id: "lt-basis",
        chapterId: "linear-transforms",
        title: "基向量如何决定整个变换",
        slug: "basis-transformation",
        objectives: ["理解变换由基向量的像决定", "从变换后的基向量读取变换矩阵", "理解'线性'意味着其他向量随着基向量同步变化"],
        motivation: "为什么知道两个向量去哪里了，就等于知道了整个平面去哪里了？因为平面上任意向量都可以用两个基向量的线性组合表示——基向量怎么变，平面就怎么变。",
        intuition: "在空间中画一个'L'形标记：i = (1,0) 沿 x 轴方向，j = (0,1) 沿 y 轴方向。整个空间的变换已经蕴含在 i 和 j 的新位置上，因为任意向量 v = (a,b) = ai + bj 会变成 a·(新i) + b·(新j)。",
        definition: "一旦知道了变换后的 i 和 j，我们就能确定整个变换。变换矩阵的第一列就是变换后的 i，第二列就是变换后的 j。因为任意 v = xi + yj 变换后 = x·T(i) + y·T(j)。",
        formulaLatex: "T\\begin{pmatrix} x \\\\ y \\end{pmatrix} = x \\cdot T\\begin{pmatrix} 1 \\\\ 0 \\end{pmatrix} + y \\cdot T\\begin{pmatrix} 0 \\\\ 1 \\end{pmatrix}",
        formulaExplanation: "变换矩阵 = [T(i) | T(j)]，即两列分别是变换后的基向量。",
        example: {
          problem: "如果 T(i) = (2, 1)，T(j) = (0, 3)，写出 T 的矩阵并求 T(4, 5)。",
          steps: [
            { description: "矩阵第1列 = T(i)", latex: "T = \\begin{pmatrix} 2 & 0 \\\\ 1 & 3 \\end{pmatrix}" },
            { description: "T(4,5) = 4·T(i) + 5·T(j)", latex: "= 4\\begin{pmatrix}2\\\\1\\end{pmatrix} + 5\\begin{pmatrix}0\\\\3\\end{pmatrix} = \\begin{pmatrix}8\\\\19\\end{pmatrix}" },
          ],
          answer: "T = [2 0; 1 3], T(4,5) = (8, 19)",
          answerLatex: "T = \\begin{pmatrix}2 & 0 \\\\ 1 & 3\\end{pmatrix}, T\\begin{pmatrix}4\\\\5\\end{pmatrix} = \\begin{pmatrix}8\\\\19\\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "混淆行和列的方向（行列不分）", correction: "T(i) 是第一列，T(j) 是第二列。矩阵是 [T(i) | T(j)] 不是 [T(i); T(j)]。" },
        ],
        summary: ["变换由基向量的像完全决定", "矩阵列向量 = 变换后的基向量", "任意向量跟着基向量等比例变化"],
        selfCheck: ["如果 T(i) = (0, 2) 和 T(j) = (-3, 0)，画出原来 1×1 正方形变换后的形状。"],
      },
      {
        id: "lt-visual",
        chapterId: "linear-transforms",
        title: "二维与三维可视化",
        slug: "transform-visualization",
        objectives: ["在坐标平面上画出变换效果", "观察变换对网格的影响", "理解三维变换在二维上的投影"],
        motivation: "眼睛看到的变化，胜过一百个公式。可视化帮助建立矩阵和几何之间的桥梁。",
        intuition: "拖拽矩阵的元素 —— 看着网格和图形随之变化，基向量跟着动，面积跟着变。这种即时的视觉反馈让抽象的矩阵变得可感知、可触摸。",
        definition: "可视化线性变换的最有效方式：同时画变换前的原图和变换后的图像。关键观察：(1) 网格是否保持平行？(2) 面积缩放了多少？(3) 方向是否被翻转？",
        formulaLatex: "\\text{原始图形} \\xrightarrow{M} \\text{变换后的图形}",
        formulaExplanation: "网格线和特定图形的变换能直观展示矩阵的效果。",
        example: {
          problem: "画出矩阵 M = ┌0.5 0┐ 对方形 [0,1]×[0,1] 的变换。\n           └0   2┘",
          steps: [
            { description: "正方形顶点：(0,0)→(0,0)", latex: "T(0,0) = (0,0)" },
            { description: "(1,0)→(0.5, 0)", latex: "T(1,0) = (0.5, 0)" },
            { description: "(0,1)→(0, 2)", latex: "T(0,1) = (0, 2)" },
            { description: "(1,1)→(0.5, 2)", latex: "T(1,1) = (0.5, 2)" },
            { description: "结果：宽缩到0.5，高拉到2倍", latex: "\\text{矩形变成 0.5×2 的长方形}" },
          ],
          answer: "正方形变为 0.5×2 的矩形",
          answerLatex: "\\text{面积缩放因子} = \\det(M) = 1",
        },
        commonMistakes: [],
        summary: ["变换后网格保持平行 = 线性变换", "面积缩放 = |det|", "行列式为负 = 翻转方向"],
        selfCheck: ["观察面积，为什么缩放因子是 |det| 而不是 det？", "画出 ┌1 1:0 1┐（剪切）对方形的影响。"],
      },
    ],
  },
  {
    id: "determinants",
    number: 5,
    title: "行列式",
    description: "理解行列式作为'面积/体积缩放因子'的几何意义，掌握计算方法。",
    prerequisites: ["矩阵运算", "线性变换"],
    teachingPoints: [
      "行列式=0 意味着变换将空间压缩到更低维",
      "行列式才正负号表示方向是否翻转",
      "行列式的代数性质和几何意义一一对应",
    ],
    commonMisconceptions: [
      "认为行列式可以用于非方阵（行列式只对方阵定义）",
      "认为 det(A+B) = det(A) + det(B)（行列式不满足加法）",
      "认为 det(kA) = k·det(A)（实际是 kⁿ·det(A)，n 为矩阵阶数）",
    ],
    discussionQuestions: [
      "为什么 det(A)=0 等价于 A 不可逆？从几何角度如何理解？",
      "如果两个矩阵的乘积行列式是0，能推出什么？",
    ],
    knowledgePoints: [
      {
        id: "det-computation",
        chapterId: "determinants",
        title: "二阶、三阶行列式的计算",
        slug: "determinant-computation",
        objectives: ["掌握二阶行列式 ad-bc", "掌握三阶行列式的 Sarrus 法则", "理解行列式的递归定义"],
        motivation: "行列式提供了一个数字，这个数字揭示了矩阵是否可逆、变换是否会压平空间、面积放大了多少——一个数字，同时告诉你三件事。",
        intuition: "二阶行列式 ad-bc = 平行四边形（以矩阵两列为边的平行四边形）的面积。正的 = 方向保持；负的 = 方向翻转。这个数值就是变换后单位正方形面积的放大倍数。",
        definition: "对 2×2 矩阵 det(A) = ad-bc。对 3×3 矩阵，可用 Sarrus 法则：主对角线方向的三条乘积之和减去副对角线方向的三条乘积之和。",
        formulaLatex: "\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc \\\\ \\det\\begin{pmatrix} a_{11} & a_{12} & a_{13} \\\\ a_{21} & a_{22} & a_{23} \\\\ a_{31} & a_{32} & a_{33} \\end{pmatrix} = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{13}a_{22}a_{31} - a_{11}a_{23}a_{32} - a_{12}a_{21}a_{33}",
        formulaExplanation: "二阶是一对对角线的差。三阶是三对对角线的差（主对角线方向三条+，副对角线方向三条-）。",
        example: {
          problem: "计算行列式 |3 1|\n          |2 4|",
          steps: [
            { description: "ad - bc", latex: "3 \\times 4 - 1 \\times 2 = 12 - 2 = 10" },
          ],
          answer: "10",
          answerLatex: "\\det = 10",
        },
        commonMistakes: [
          { mistake: "三阶时漏掉或加错对角线方向", correction: "主对角线方向（左上→右下）为正号，副对角线方向（右上→左下）为负号。" },
          { mistake: "把行列式和矩阵混淆，用矩阵加减规则算行列式", correction: "行列式是一个数字，不是矩阵。det(A+B) ≠ det(A)+det(B)。" },
        ],
        summary: ["二阶：ad - bc", "三阶：Sarrus（三条正减三条负）", "行列式是数字，不是矩阵"],
        selfCheck: ["自己编一个二阶矩阵，计算其行列式。", "三阶行列式为零至少意味着什么？"],
      },
      {
        id: "det-area",
        chapterId: "determinants",
        title: "面积和体积的缩放意义",
        slug: "determinant-area",
        objectives: ["理解行列式 = 面积/体积缩放因子", "用行列式求平行四边形的面积", "扩展到 n 维空间中的 n 维体积"],
        motivation: "微积分里 dxdy 是面积元素。行列式告诉你：坐标变换后，原来的 dxdy 变成了多少倍的新面积元素。这在多元积分换元时至关重要。",
        intuition: "一个 1×1 的单位正方形，经过矩阵 M 的变换后变成平行四边形。平行四边形的面积恰好是 |det(M)|。如果 det(M) > 0，正方形保持正面朝上；det(M) < 0，正方形'翻了个面'（相当于被翻转了）。",
        definition: "|det(M)| = 变换后 n 维平行超体的 n 维体积（以变换前单位 n 维正方体的体积为 1）。两列向量张成的平行四边形的面积 = |det([v₁ v₂])|。",
        formulaLatex: "\\text{面积} = |\\det(A)| \\times \\text{（原面积）}",
        formulaExplanation: "det 的绝对值 = 面积缩放因子。对任一由两个列向量张成的平行四边形，面积 = |det(列向量矩阵)|。",
        example: {
          problem: "求由向量 v₁=(3,1) 和 v₂=(1,2) 张成的平行四边形的面积。",
          steps: [
            { description: "写成矩阵", latex: "\\begin{pmatrix} 3 & 1 \\\\ 1 & 2 \\end{pmatrix}" },
            { description: "计算行列式", latex: "\\det = 3\\times2 - 1\\times1 = 5" },
            { description: "面积 = |det|=5", latex: "\\text{面积} = 5" },
          ],
          answer: "面积 = 5",
          answerLatex: "\\text{面积} = |\\det| = 5",
        },
        commonMistakes: [
          { mistake: "忘记取绝对值", correction: "面积总是非负的，是 |det|。行列式本身可能是负的。" },
        ],
        summary: ["|det| = 面积缩放因子", "平行四边形的面积 = |det(列矩阵)|", "负的行列式 = 翻转 + 缩放"],
        selfCheck: ["如果把两个向量对调顺序（列交换），行列式会怎么变？", "一个行列式为 0.5 的矩阵是'压扁'还是'拉伸'？"],
      },
      {
        id: "det-sign",
        chapterId: "determinants",
        title: "正负号与方向变化",
        slug: "determinant-sign",
        objectives: ["理解行列式正负号的几何含义", "区分保持方向和翻转方向", "理解定向（orientation）的概念"],
        motivation: "为什么行列式有时是负的？面积不能是负的。负号的意思是——变换过程会翻转方向：就好像你把一张纸翻了个面。这个'翻转'的信息无法用绝对值表达。",
        intuition: "想象一个右手坐标系（x 轴向右，y 轴向上）。如果变换后，x 轴跑到了 y 轴的右边（从 x 到 y 是顺时针而不是逆时针），那方向就被翻转了。行列式的负号记录了这个翻转。",
        definition: "如果 det > 0，变换保持了旋转方向（顺时针变顺时针，逆时针变逆时针）。如果 det < 0，变换翻转了方向。如果 det = 0，变换把空间压到更低维度（无法判断方向）。",
        formulaLatex: "\\det > 0 \\Rightarrow \\text{保持定向}, \\quad \\det < 0 \\Rightarrow \\text{翻转定向}, \\quad \\det = 0 \\Rightarrow \\text{降维}",
        formulaExplanation: "负号出现在'二维空间被翻转'的情况：原来在 x 轴上的点跑到 y 轴下面去了。",
        example: {
          problem: "矩阵 M = ┌0 1┐ 的行列式 = -1。动画中发生了什么？\n           └1 0┘",
          steps: [
            { description: "行列式 = 0×0-1×1 = -1", latex: "\\det = -1" },
            { description: "|det|=1（面积不变）", latex: "|\\det| = 1" },
            { description: "det<0：方向翻转", latex: "\\text{i = (0,1), j = (1,0)：坐标轴互换且翻转}" },
          ],
          answer: "面积不变，方向翻转",
          answerLatex: "\\det = -1，翻转定向",
        },
        commonMistakes: [
          { mistake: "认为负的行列式意味着面积是负的", correction: "面积是非负的。负号是方向信息，不是面积信息。" },
        ],
        summary: ["+ → 保持方向", "- → 翻转方向", "0 → 降维（无法说方向）"],
        selfCheck: ["如果一个 3D 变换的行列式 = -2，物体发生了什么？", "为什么零行列式无法判断方向？"],
      },
      {
        id: "det-zero",
        chapterId: "determinants",
        title: "行列式为零意味着什么",
        slug: "determinant-zero",
        objectives: ["理解 det=0 的几何含义", "将 det=0 与降维联系起来", "识别行列式为零的情况"],
        motivation: "行列式为零的矩阵会把空间'压扁'——从三维压到二维、从二维压到一维甚至一点。这就像投影机把立方体投成正方形影子：信息被压缩了，无法还原回去。",
        intuition: "如果两列向量共线（方向相同或相反），它们张成的'平行四边形'退化为一条线段，面积自然为零。如果三列共面，平行四面体退化，体积为零。这就是行列式为零的本质：列向量线性相关。",
        definition: "det(A)=0 ⟺ 列向量线性相关 ⟺ A 不可逆 ⟺ 变换把 n 维空间压缩到更低维度 ⟺ Ax=0 有非零解。这些含义完全等价。",
        formulaLatex: "\\det(A) = 0 \\Longleftrightarrow \\begin{cases} \\text{列向量线性相关} \\\\ A \\text{不可逆} \\\\ \\text{变换降维} \\\\ \\operatorname{rank}(A) < n \\end{cases}",
        formulaExplanation: "行列式为零等价于满秩（rank=n）不成立。变换的信息丢失了，无法还原。",
        example: {
          problem: "判断矩阵 ┌1 2┐ 的行列式并解释其几何含义。\n            └2 4┘",
          steps: [
            { description: "行列式计算", latex: "\\det = 1\\times4 - 2\\times2 = 0" },
            { description: "det=0：列向量 (1,2) 和 (2,4) 共线", latex: "\\text{第二列} = 2\\times\\text{第一列}" },
            { description: "变换将二维平面压到一条直线上", latex: "\\text{所有点落到一条直线上}" },
          ],
          answer: "det=0，变换降维到一条直线",
          answerLatex: "\\det = 0，降维",
        },
        commonMistakes: [
          { mistake: "认为 det=0 的矩阵一定很特殊很少见", correction: "det=0 的矩阵非常常见——只要列向量线性相关就会出现。几乎所有'有重复信息'的矩阵都行列式为零。" },
        ],
        summary: ["det=0 ↔ 列线性相关 ↔ 降维 ↔ 不可逆 ↔ 方程有无穷多解或无解", "这是线性代数最核心的等价关系之一"],
        selfCheck: ["举三个例子说明 det=0 的情况。", "如果 3×3 矩阵的第3列 = 第1列+第2列，行列式是多少？"],
      },
      {
        id: "det-inverse",
        chapterId: "determinants",
        title: "行列式与矩阵可逆性的关系",
        slug: "determinant-inverse",
        objectives: ["理解 det(A)≠0 ↔ A 可逆", "理解逆矩阵存在的条件", "知道 det(A⁻¹) = 1/det(A)"],
        motivation: "要判断一个矩阵是否可逆，一行一行地做高斯消元很慢。但算一个行列式很快——如果是零，直接知道不可逆；不是零，一定可逆。行列式是判断可逆性的'快速体检指标'。",
        intuition: "如果变换把空间压平了（det=0），就没办法把压平的影子还原成原来的立体。不可逆就是'不存在还原操作'。如果变换没有压平（det≠0），总有一个逆操作用来还原。",
        definition: "A⁻¹ 存在 ⟺ det(A) ≠ 0。且 det(A⁻¹) = 1/det(A)。A 可逆时称为非奇异矩阵（nonsingular）；不可逆时称为奇异矩阵（singular）。",
        formulaLatex: "\\det(A) \\neq 0 \\iff A \\text{可逆}, \\quad \\det(A^{-1}) = \\frac{1}{\\det(A)}",
        formulaExplanation: "逆变换的面积缩放因子 = 原变换的倒数（先缩2倍再缩1/2 = 原样）。",
        example: {
          problem: "已知矩阵 A 的 det = 0.5，且 A 可逆。det(A⁻¹) = 多少？",
          steps: [
            { description: "det(A⁻¹) = 1/det(A)", latex: "\\det(A^{-1}) = \\frac{1}{0.5} = 2" },
            { description: "逆变换复原：原面积缩小到 0.5，逆变换放大到 2 倍，乘积为 1", latex: "\\det(A)\\det(A^{-1}) = 1" },
          ],
          answer: "det(A⁻¹) = 2",
          answerLatex: "\\det(A^{-1}) = 2",
        },
        commonMistakes: [
          { mistake: "认为 det(A)·det(B) = det(A·B) 对任意矩阵成立", correction: "这个公式是对的！但 det(A+B) ≠ det(A)+det(B)。" },
        ],
        summary: ["可逆 ↔ det≠0", "det(A⁻¹) = 1/det(A)", "det(AB) = det(A)·det(B)"],
        selfCheck: ["如果两个矩阵 AB 的行列式 = 6，且 det(A)=2，那么 det(B)=? ", "det(Aᵀ) = det(A) 吗？为什么？"],
      },
    ],
  },
  {
    id: "vector-spaces",
    number: 6,
    title: "向量空间",
    description: "从'集合+运算'的视角重新审视之前的向量和矩阵，建立子空间、基、维数和秩等核心抽象概念。",
    prerequisites: ["向量基础", "矩阵运算", "线性方程组"],
    teachingPoints: [
      "向量空间是满足封闭性的一类集合",
      "基是最小的生成集，维数是基中向量的个数",
      "秩衡量矩阵产生的列空间和行空间的维数",
    ],
    commonMisconceptions: [
      "认为向量一定是箭头（向量空间中的元素可以是函数、矩阵等任何满足运算封闭的对象）",
      "混淆维数和坐标分量数量",
      "认为子空间一定比原空间小",
    ],
    discussionQuestions: [
      "为什么向量空间的定义必须包含'封闭性'？",
      "如果去掉零向量，集合还能是向量空间吗？",
    ],
    knowledgePoints: [
      {
        id: "vs-span-dependence",
        chapterId: "vector-spaces",
        title: "张成、线性相关与线性无关",
        slug: "span-dependence",
        objectives: ["理解张成（span）= 所有线性组合组成集合", "判断一组向量是否线性相关", "理解线性无关 = 没有冗余信息"],
        motivation: "如果已经有了一个助手在 x 方向工作，再雇一个人也在 x 方向做事——第二个人是冗余的（线性相关）。但如果两个人各自在 x 和 y 方向上工作——组合起来能覆盖整个平面（线性无关）。",
        intuition: "张成：给定几个向量，它们所有可能的线性组合构成一个'覆盖范围'（子空间）。线性相关：其中一个向量可以被其他向量的线性组合代替（它没有扩大覆盖范围）。线性无关：每个向量都'贡献了新方向'。",
        definition: "张成 span{v₁,...,vₙ} = {c₁v₁+...+cₙvₙ | cᵢ∈ℝ}。向量组线性相关 ⟺ 存在不全为零的系数使 c₁v₁+...+cₙvₙ = 0。矩阵的列向量线性相关 ⟺ det=0（方阵）或秩<列数。",
        formulaLatex: "\\operatorname{span}\\{v_1, \\ldots, v_k\\} = \\{c_1 v_1 + \\cdots + c_k v_k \\mid c_i \\in \\mathbb{R}\\}",
        formulaExplanation: "张成 = 所有可能的线性组合。通过调整每个向量的'重量'（系数），张成出整个子空间。",
        example: {
          problem: "判断 v₁=(1,0), v₂=(2,0) 是否线性无关。span{v₁,v₂} 是什么？",
          steps: [
            { description: "v₂ = 2v₁（一个是另一个的倍数）", latex: "v_2 = 2v_1" },
            { description: "线性相关（有冗余）", latex: "\\text{线性相关}" },
            { description: "张成空间 = x轴上的所有点", latex: "\\operatorname{span}\{v_1,v_2\} = \\{(x,0) \\mid x\\in\\mathbb{R}\\}" },
          ],
          answer: "线性相关，张成空间 = x 轴",
          answerLatex: "\\text{线性相关, span = x轴}",
        },
        commonMistakes: [
          { mistake: "认为两个非零向量一定线性无关", correction: "如果一个是另一个的倍数，它们就线性相关。必须指向'不同的方向'才无关。" },
        ],
        summary: ["张成 = 所有线性组合覆盖的范围", "线性相关 = 有冗余向量存在", "线性无关 = 每个向量都扩展了覆盖范围"],
        selfCheck: ["两个在三维空间中的向量，什么时候线性无关？它们的张成空间是什么样子？"],
      },
      {
        id: "vs-basis-dim",
        chapterId: "vector-spaces",
        title: "基、维数和坐标",
        slug: "basis-dimension",
        objectives: ["理解基 = 极大线性无关组 = 极小的张成集", "理解维数 = 基中向量的个数", "理解同一向量在不同基下的坐标不同"],
        motivation: "地图上的'东西南北'是一个坐标系统。经纬度是另一个。同一个点在不同系统中的坐标不同。基就是坐标系统的基础方向。",
        intuition: "基是空间的'骨架'：最少的向量，但张成整个空间。就像建房子只需要横梁和纵梁两根骨架，但能通过调节每根的长度来触达房子里的每个点。",
        definition: "基是最小的张成集 = 最大的线性无关集。空间的维数 = 任意一组基中向量的个数（这个数是固定的，无论选哪组基）。同一个向量在不同基下的坐标一般不同。",
        formulaLatex: "\\dim(V) = \\text{基中向量的个数} \\\\ v = c_1 b_1 + \\cdots + c_n b_n, \\quad \\text{坐标} = (c_1, \\ldots, c_n)",
        formulaExplanation: "坐标依赖于基的选择。在标准基下，v 的坐标就是 v 本身的分量。",
        example: {
          problem: "证明二维空间中任意两个线性无关的向量构成一组基。",
          steps: [
            { description: "线性无关 → 不共线", latex: "v_1 \\neq k v_2" },
            { description: "任意二维向量可由它们线性组合", latex: "\\forall w \\in \\mathbb{R}^2, \\exists c_1,c_2: w = c_1 v_1 + c_2 v_2" },
            { description: "满足基的两个条件", latex: "\\text{线性无关 + 张成全空间 = 基}" },
          ],
          answer: "任意两个线性无关的二维向量构成基",
          answerLatex: "\\{v_1, v_2\\} \\text{线性无关} \\Rightarrow \\text{基}",
        },
        commonMistakes: [
          { mistake: "认为维数就是向量的分量个数", correction: "二维平面的维数是2（需要2个方向），但二维平面中的点有2个分量。分量的个数恰好等于维数是因为在标准基下。" },
        ],
        summary: ["基 = 极小的生成集 = 极大的无关集", "维数 = 基的大小（固定、有基的选择无关）", "坐标依基而定"],
        selfCheck: ["为什么空间的每一组基都有相同数量的向量？", "令 b₁=(1,1), b₂=(-1,1)，v=(3,1) 在这个基下的坐标是多少？"],
      },
      {
        id: "vs-subspaces",
        chapterId: "vector-spaces",
        title: "列空间、行空间和零空间",
        slug: "four-subspaces",
        objectives: ["理解列空间 = 所有可能输出的集合", "理解行空间 = 行的张成空间", "理解零空间（核）= 被映射到零的向量的集合"],
        motivation: "什么样的 b 使得方程组 Ax=b 有解？答案是：b 必须在 A 的列空间中。'A 把什么向量映射为零？'答案是：零空间中的向量。这两个子空间完整描述了矩阵的作用。",
        intuition: "列空间 Col(A)：矩阵的列向量张成的子空间，代表'矩阵能把输入变成什么样子'。零空间 Nul(A)：所有被矩阵压成零的输入向量的集合，代表'矩阵会损失什么信息'。",
        definition: "Col(A) = span{矩阵A的列} = {Ax | x∈ℝⁿ}（值域）。Row(A) = span{矩阵A的行}。Nul(A) = {x | Ax=0}（被映射为零的向量）。秩 = dim(Col(A)) = dim(Row(A))。秩定理：dim(Col(A)) + dim(Nul(A)) = n。",
        formulaLatex: "\\operatorname{Col}(A) = \\{A\\mathbf{x} \\mid \\mathbf{x} \\in \\mathbb{R}^n\\} \\\\ \\operatorname{Nul}(A) = \\{\\mathbf{x} \\mid A\\mathbf{x} = \\mathbf{0}\\} \\\\ \\operatorname{rank}(A) + \\dim\\operatorname{Nul}(A) = n",
        formulaExplanation: "列空间 = 矩阵的输出范围 = 值域。零空间 = 被压成零的输入范围 = 核。它们的维数之和 = 输入空间的维数。",
        example: {
          problem: "矩阵 A = ┌1 2┐ 的列空间和零空间各是什么？\n           └2 4┘",
          steps: [
            { description: "列向量：v₁=(1,2), v₂=(2,4)=2v₁", latex: "\\text{列空间} = \\{(t, 2t) \\mid t\\in\\mathbb{R}\\}（一条直线）" },
            { description: "解 Ax=0 → x+2y=0 → x=-2y", latex: "\\text{零空间} = \\{(-2t, t) \\mid t\\in\\mathbb{R}\\}" },
            { description: "rank=1, n=2", latex: "\\dim\\operatorname{Col} + \\dim\\operatorname{Nul} = 1 + 1 = 2 = n" },
          ],
          answer: "列空间=直线 y=2x，零空间=直线 y=-x/2",
          answerLatex: "\\operatorname{Col}(A) = \\{(t, 2t)\\}, \\operatorname{Nul}(A) = \\{(-2t, t)\\}",
        },
        commonMistakes: [
          { mistake: "认为列向量线性无关时零空间为空（错误！用'零'字面意思）", correction: "零空间永远包含零向量。它是'被映射为零的所有向量'的集合，不是'空集'。" },
        ],
        summary: ["Col(A) = 可能输出的集合", "Nul(A) = 被映射为零的输入集合", "秩定理：rank + nullity = n"],
        selfCheck: ["dim(Col) + dim(Nul) = n 的含义是什么？", "如果 A 是 5×3 矩阵且秩为 2，它的零空间维数是多少？"],
      },
      {
        id: "vs-rank",
        chapterId: "vector-spaces",
        title: "秩的含义",
        slug: "rank-meaning",
        objectives: ["理解秩的多重含义", "用秩判断线性方程组解的情况", "理解秩是矩阵产生有效信息维度"],
        motivation: "一张照片被压缩到JPEG格式后，文件大小缩小了。这是因为原图有很多'冗余信息'。矩阵的秩就是它的'有效信息维度'——秩越小，信息越冗余。",
        intuition: "秩 = 独立列的数量 = 独立行的数量 = 有效维度数。秩=1 的矩阵意味着所有信息可以通过一个方向表达（所有列/行都成比例）。秩=n（满秩）意味着矩阵没有冗余，信息最丰富。",
        definition: "秩 rank(A)= 最大线性无关列数 = 最大线性无关行数 = 行阶梯形中非零行数 = dim(Col(A)). 满秩 ↔ 可逆（方阵时）↔ 行列式≠0。",
        formulaLatex: "\\operatorname{rank}(A) = \\text{独立列数} = \\text{独立行数} \\leq \\min(m, n)",
        formulaExplanation: "秩是独立信息的维数。一个 m×n 矩阵的秩不能超过行数和列数中较小的那个。",
        example: {
          problem: "矩阵 ┌1 2 3┐\n      └2 4 6┘ 的秩是多少？",
          steps: [
            { description: "第2行 = 2×第1行", latex: "R_2 = 2R_1" },
            { description: "只有一个独立行", latex: "\\operatorname{rank} = 1" },
            { description: "验证：所有列也在同一条直线上", latex: "\\text{列空间是一维的}" },
          ],
          answer: "秩=1",
          answerLatex: "\\operatorname{rank} = 1",
        },
        commonMistakes: [
          { mistake: "认为零矩阵秩 = 1", correction: "零矩阵的秩 = 0（没有任何独立信息）。" },
        ],
        summary: ["秩 = 独立信息维度", "秩=0 → 全零矩阵", "秩=n → 满秩（可逆）"],
        selfCheck: ["为什么秩不能超过行列数的最小值？", "说明为什么 rank(A) = rank(Aᵀ)。"],
      },
      {
        id: "vs-geometry",
        chapterId: "vector-spaces",
        title: "用几何图形解释抽象概念",
        slug: "subspace-geometry",
        objectives: ["可视化子空间（点、直线、平面、整个空间）", "理解投影到子空间", "理解维度递降"],
        motivation: "三维空间的子空间有三种：过原点的直线（1D）、过原点的平面（2D）、整个空间（3D），以及原点本身（0D）。这是你能亲眼看到的四个层次。",
        intuition: "每个子空间都像一个更小的'世界'，自己满足向量空间的所有条件。封闭性意味着：在这个小世界里做任何向量运算，结果还是在小世界里。就像在一条直线上走，永远不会离开这条直线。",
        definition: "在 R² 中，子空间有：{0}（原点）、过原点的直线、整个平面。在 R³ 中增加：过原点的平面。矩阵的列空间、行空间和零空间都是子空间，其维数不超过所在空间的维数。",
        formulaLatex: "\\text{子空间}: \\{0\\} \\subset \\text{直线} \\subset \\text{平面} \\subset \\mathbb{R}^3",
        formulaExplanation: "每个子空间都是'缩小版'的向量空间，满足封闭性。最小为 {0}（0维），最大为整个空间（n维）。",
        example: {
          problem: "描述 R³ 中方程 x+y+z=0 确定的子空间。",
          steps: [
            { description: "所有满足 x+y+z=0 的点", latex: "z = -x - y" },
            { description: "有两个自由方向（x 和 y），被 z 约束", latex: "\\text{维数}=2，是一个过原点的平面" },
            { description: "法向量 (1,1,1) 垂直于此平面", latex: "\\text{法向量}= (1, 1, 1)" },
          ],
          answer: "过原点的平面（2维子空间）",
          answerLatex: "\\{(x, y, -x-y) \\mid x,y\\in\\mathbb{R}\\}，2维子空间",
        },
        commonMistakes: [
          { mistake: "认为二维平面上的曲线是子空间", correction: "子空间中的直线必须是'直'的（过原点）。曲线不是子空间（乘以标量可能离开曲线）。" },
        ],
        summary: ["在 Rⁿ 中，子空间维数可以从 0 到 n", "每个线性方程削减一个维度", "ker(A) 和 col(A) 都可以几何可视化"],
        selfCheck: ["R⁴ 的子空间可能有哪些维数？", "为什么子空间必须过原点？"],
      },
    ],
  },
  {
    id: "eigenvalues",
    number: 7,
    title: "特征值与特征向量",
    description: "理解矩阵作用在特定方向上不变方向的特殊属性，掌握计算方法和应用价值。",
    prerequisites: ["矩阵运算", "行列式", "向量空间"],
    teachingPoints: [
      "特征向量在线性变换下方向不变（只能被拉伸或缩短）",
      "特征值 = 拉伸倍数",
      "对角化 = 换一组好基使得变换变得非常简单",
    ],
    commonMisconceptions: [
      "认为每个矩阵都有 n 个实数特征值",
      "认为特征向量一定是唯一的",
      "认为特征值一定是整数",
    ],
    discussionQuestions: [
      "为什么零向量不被视为特征向量？",
      "如果特征值是负数，几何上意味着什么？",
      "什么样的变换没有实数特征值？",
    ],
    knowledgePoints: [
      {
        id: "eig-concept",
        chapterId: "eigenvalues",
        title: "概念与几何直觉",
        slug: "eigenvalue-concept",
        objectives: ["理解特征向量：变换后方向不变的向量", "理解特征值：沿特征向量方向的缩放因子", "用几何直观感受特征分解"],
        motivation: "当你斜着推一个箱子，箱子不一定朝你推的方向走——它朝一个'自然的、不受干扰的方向'走。矩阵也有这样的方向：特征方向——向量朝这个方向放，矩阵只会拉伸/缩短它，不会改变它的方向。",
        intuition: "将矩阵想象成一个拉伸机器。大多数向量进去后方向和长度都会改变。但某些特殊方向上的向量进去后，方向保持不变，只被拉长或缩短（或者翻转然后拉长/缩短）。这些特殊方向就是特征向量方向，拉伸倍数就是特征值。",
        definition: "非零向量 v 满足 Av = λv，则称 v 是 A 的特征向量，λ 是对应的特征值。A 作用于 v 只需要标量乘法（不会改变方向）。特征向量可以缩放，即如果 v 是特征向量，kv 也是（k≠0）。",
        formulaLatex: "A\\vec{v} = \\lambda \\vec{v} \\quad (\\vec{v} \\neq \\vec{0})",
        formulaExplanation: "Av 是应用变换后的向量。λv 是原向量沿同一方向伸缩 λ 倍。等式表示：作用于 v 上的变换等价于标量乘法。",
        example: {
          problem: "验证对于 A=┌2 0┐，v=(1,0) 是特征向量并求特征值。\n              └0 3┘",
          steps: [
            { description: "计算 Av", latex: "A\\begin{pmatrix}1\\\\0\\end{pmatrix} = \\begin{pmatrix}2\\\\0\\end{pmatrix}" },
            { description: "检查是否方向不变", latex: "\\begin{pmatrix}2\\\\0\\end{pmatrix} = 2\\begin{pmatrix}1\\\\0\\end{pmatrix} = \\lambda v" },
            { description: "λ=2，方向不变 ✓", latex: "\\lambda = 2" },
          ],
          answer: "v是特征向量，λ=2",
          answerLatex: "v = \\begin{pmatrix}1\\\\0\\end{pmatrix}, \\lambda = 2",
        },
        commonMistakes: [
          { mistake: "把 Av=λv 写成 Av=λ（漏掉了 v）", correction: "特征向量满足 Av = λv，等式两边都是向量，不是标量。" },
          { mistake: "认为 λ=0 不算特征值", correction: "λ=0 也是特征值（此时特征向量被变换映射为零向量，但方向仍'不变'——任何方向保持为零）。" },
        ],
        summary: ["特征向量 = 变换下方向不变的向量", "特征值 λ = 沿特征向量方向的拉伸倍数", "如果 λ<0 则翻转（反向后拉伸）"],
        selfCheck: ["λ=1 意味着什么？（变换在这个方向上没有变化）", "说出至少一个 Av=λv 在实际中的例子。", "旋转 90° 的矩阵有实数特征向量吗？"],
      },
      {
        id: "eig-computation",
        chapterId: "eigenvalues",
        title: "计算方法",
        slug: "eigenvalue-computation",
        objectives: ["写出特征方程 det(A-λI)=0", "求解特征多项式得到特征值", "对每个特征值求特征向量"],
        motivation: "如果特征值像'特殊方向上的放大率'，那怎么找到它们？通过解特征方程 det(A-λI)=0——这把你从几何问题转化为代数方程。",
        intuition: "det(A-λI)=0 的意思是：存在一个方向，沿着这个方向，(A-λI) 把空间压扁（行列式=0）。这个方向中的向量被映射为零向量，即 Av-λv=0，也就是 Av=λv。",
        definition: "步骤：(1) 写出特征多项式 p(λ)=det(A-λI)；(2) 解 p(λ)=0 得特征值；(3) 对每个 λ，解 (A-λI)v=0 得特征向量空间。对于 n×n 矩阵，最多有 n 个特征值（考虑重数）。",
        formulaLatex: "\\det(A - \\lambda I) = 0 \\quad \\Rightarrow \\quad p(\\lambda) = 0",
        formulaExplanation: "A-λI 是将 A 的对角线元素各减去 λ。它的行列式为零意味着 λ 是特征值。",
        example: {
          problem: "求矩阵 A=┌1 2┐ 的特征值和特征向量。\n               └2 1┘",
          steps: [
            { description: "A-λI", latex: "\\begin{pmatrix} 1-\\lambda & 2 \\\\ 2 & 1-\\lambda \\end{pmatrix}" },
            { description: "特征方程", latex: "\\det = (1-\\lambda)^2 - 4 = \\lambda^2 - 2\\lambda - 3 = 0" },
            { description: "解二次方程", latex: "(\\lambda - 3)(\\lambda + 1) = 0 \\Rightarrow \\lambda_1=3, \\lambda_2=-1" },
            { description: "λ₁=3: 解(A-3I)v=0", latex: "\\begin{pmatrix}-2&2\\\\2&-2\\end{pmatrix}\\begin{pmatrix}x\\\\y\\end{pmatrix}=0 \\Rightarrow v_1=(1,1)" },
            { description: "λ₂=-1: 解(A+I)v=0", latex: "\\begin{pmatrix}2&2\\\\2&2\\end{pmatrix}\\begin{pmatrix}x\\\\y\\end{pmatrix}=0 \\Rightarrow v_2=(1,-1)" },
          ],
          answer: "λ₁=3, v₁=(1,1); λ₂=-1, v₂=(1,-1)",
          answerLatex: "\\lambda_1=3, v_1=(1,1); \\lambda_2=-1, v_2=(1,-1)",
        },
        commonMistakes: [
          { mistake: "用代数余子式展开时符号出错", correction: "det(A-λI) 展开时注意符号，特别是对角线以外的元素。" },
          { mistake: "解出特征值后不求解特征向量", correction: "特征值只是'拉伸因子'，特征向量告诉你'朝哪个方向拉伸'。" },
        ],
        summary: ["写出 A-λI", "求 det(A-λI)=0 得特征值", "对每个 λ，解 (A-λI)v=0 得特征向量"],
        selfCheck: ["为什么 n×n 方阵最多有 n 个特征值？", "如果特征多项式有复数根怎么办？"],
      },
      {
        id: "eig-matrix-action",
        chapterId: "eigenvalues",
        title: "矩阵对特征向量的作用",
        slug: "eigenvalue-matrix-action",
        objectives: ["理解 Aⁿv = λⁿv", "用特征值预测迭代行为", "理解特征值大小决定长期行为"],
        motivation: "如果每个小时做一次变换，重复100个小时后系统会演化成什么样？如果是随机矩阵，计算量爆炸。但如果是特征空间中的向量，答案是简单的：每个方向上按 λⁿ 缩放！",
        intuition: "把任意向量分解为特征向量的和：v = c₁v₁ + c₂v₂。每次变换后：Av = c₁λ₁v₁ + c₂λ₂v₂。重复 n 次变换后：Aⁿv = c₁λ₁ⁿv₁ + c₂λ₂ⁿv₂。如果 |λ₁|>1，该方向会越来越'爆炸'；如果 |λ₁|<1，会越来越缩——这就是长期行为的本质。",
        definition: "Aⁿv = λⁿv（v 是特征向量）。若任一特征值 |λ|>1，迭代 Aⁿ 会发散（膨胀）。若所有 |λ|<1，会收敛到零（收缩）。这正是 Google 的 PageRank 算法、差分方程稳定性分析等的基础。",
        formulaLatex: "A^n \\vec{v} = \\lambda^n \\vec{v}, \\quad \\vec{x}_n = A^n\\vec{x}_0 \\text{（迭代系统）}",
        formulaExplanation: "特征向量上的行为极其简单：标量乘法。其他向量的行为由特征分解决定。",
        example: {
          problem: "系统 xₙ₊₁ = ┌2 0┐ xₙ，初始 x₀=(1,1)。求 n→∞ 时的行为。\n            └0 0.5┘",
          steps: [
            { description: "特征值：λ₁=2, λ₂=0.5", latex: "\\lambda_1 = 2, \\lambda_2 = 0.5" },
            { description: "分解：x₀ 在 e₁ 方向有分量 1", latex: "x_0 = (1,0) + (0,1)" },
            { description: "n 步后：xₙ = (2ⁿ, 0.5ⁿ)", latex: "x_n = (2^n, 0.5^n)" },
            { description: "2ⁿ→∞（发散），0.5ⁿ→0（收敛）", latex: "\\text{第一分量发散，第二分量收敛为零}" },
          ],
          answer: "第一分量发散（爆炸），第二分量收敛（归零）",
          answerLatex: "x_n \\to (\\infty, 0)",
        },
        commonMistakes: [
          { mistake: "认为 Aⁿ = (λ₁ⁿ, λ₂ⁿ, ...) 对角矩阵（只对特征向量成立）", correction: "Aⁿv ≠ λⁿ, 而是 Aⁿv = λⁿv 仅对 v 是特征向量成立。一般向量需要分解为特征向量的和。" },
        ],
        summary: ["Aⁿv = λⁿv", "|λ|>1 → 膨胀；|λ|<1 → 收缩；|λ|=1 → 旋转或恒定", "系统长期行为由最大绝对值的特征值主导"],
        selfCheck: ["为什么只需看特征值的绝对值？", "如果你有一套餐厅评分系统（每个餐厅的得分会受其他餐厅影响），如何用特征值分析这个系统？"],
      },
      {
        id: "eig-diagonalization",
        chapterId: "eigenvalues",
        title: "对角化的基本思想",
        slug: "diagonalization",
        objectives: ["理解对角化的条件（n个线性无关的特征向量）", "理解对角化的几何意义（换基）", "掌握对角化公式 A = PDP⁻¹"],
        motivation: "计算 A¹⁰⁰ 如果用原始矩阵乘法要做99次矩阵乘法。但如果把 A 对角化（化成对角矩阵 D），计算 D¹⁰⁰ 只需把对角线上每个元素 100 次方——一秒钟搞定。",
        intuition: "对角化就是换一个坐标系。在新的坐标系（由特征向量组成的基）下，原先复杂的变换变得极其简单——就是每个轴方向上的独立伸缩。变换矩阵变成了对角矩阵，对角线元素就是特征值。",
        definition: "若 n×n 矩阵 A 有 n 个线性无关的特征向量，则 A 可对角化：A = PDP⁻¹。其中 P 是特征向量列组成的矩阵，D 是对角矩阵（对角线元素为特征值）。此时 Aⁿ = PDⁿP⁻¹。",
        formulaLatex: "A = PDP^{-1}, \\quad D = \\begin{pmatrix} \\lambda_1 & 0 & \\cdots \\\\ 0 & \\lambda_2 & \\cdots \\\\ \\vdots & \\vdots & \\ddots \\end{pmatrix}",
        formulaExplanation: "P 的列是特征向量。D 的对角线是特征值。Aⁿ = PDⁿP⁻¹（计算量从 O(n³) 降到 O(n) 对每次迭代）。",
        example: {
          problem: "A = ┌2 1┐ 是否可对角化？如果可以，写出 D 和 P。\n       └0 2┘",
          steps: [
            { description: "特征值：λ=2（重根）", latex: "\\lambda = 2 \\text{（2重）}" },
            { description: "解 (A-2I)v=0: ┌0 1:0 0┐v=0 → v必为(1,0)方向", latex: "\\text{只有一个线性无关的特征向量}" },
            { description: "只有1个线性无关特征向量，n=2", latex: "\\text{不可对角化（Jordan形式）}" },
          ],
          answer: "不可对角化（缺特征向量）",
          answerLatex: "\\text{不可对角化（特征向量不够）}",
        },
        commonMistakes: [
          { mistake: "认为所有方阵都可对角化", correction: "只有具有 n 个线性无关特征向量的矩阵才可对角化。缺陷特征向量的矩阵只能用 Jordan 范式。" },
        ],
        summary: ["A = PDP⁻¹（要求 n 个线性无关特征向量）", "D = diag(λ₁,...,λₙ)", "Aⁿ = PDⁿP⁻¹"],
        selfCheck: ["为什么 A = PDP⁻¹ 不能写成 A = D（除非 P=I）？", "写出一个不可对角化矩阵的例子。"],
      },
      {
        id: "eig-applications",
        chapterId: "eigenvalues",
        title: "在图像变换、动态系统和数据分析中的简单应用",
        slug: "eigenvalue-applications",
        objectives: ["理解特征值在图像压缩中的应用思想", "理解马尔可夫过程和稳定状态", "了解 PCA 降维的基本思路"],
        motivation: "你的手机拍一张照片：1200万像素。但 jpeg 格式只用其中一小部分就基本还原了画面——它利用的是'特征压缩'的思想。Google 搜索中的 PageRank 算法、Netflix 推荐、天气预测——都依赖特征值。",
        intuition: "PCA 降维：将高维数据投影到某个特征方向（主成分）上，保留最大方差的方向（最大特征值对应）。动态系统：系统长期稳定状态 = 最大特征值对应的特征向量方向。图像压缩：丢弃小特征值对应的'微不足道的变异方向'。",
        definition: "在 PCA 中，协方差矩阵的最大特征值对应'数据变异最大的方向'（主成分1）。在差分方程中，稳定解是最大特征值对应的特征向量。在图像处理中，用特征分解选择保留主要特征方向。",
        formulaLatex: "\\text{PCA: } C\\vec{v} = \\lambda \\vec{v}, \\quad \\lambda_{\\max} = \\text{第一主成分}",
        formulaExplanation: "C 是协方差矩阵。最大特征值对应数据中方差最大的方向（最优的低维投影方向）。",
        example: {
          problem: "数据点集中在方向 (3,1) 附近。协方差矩阵 C 的特征值 λ₁=10, λ₂=1。哪一个是主成分方向？",
          steps: [
            { description: "λ₁=10（最大）对应数据最发散的方向", latex: "\\lambda_1 = 10" },
            { description: "这个方向上的方差 = λ₁ = 10", latex: "\\text{方差} = \\lambda_1" },
            { description: "第一个主成分 = λ₁ 对应的特征向量方向", latex: "\\text{主成分1方向} = \\vec{v}_1" },
          ],
          answer: "λ₁ 对应的方向（方差最大）",
          answerLatex: "\\lambda_1 为主成分（含数据方差的 91\\%）",
        },
        commonMistakes: [
          { mistake: "混淆特征值和方差", correction: "在 PCA 中：特征值=该方向上的方差。不是特征向量是方差，是特征值衡量方差。" },
        ],
        summary: ["PCA：最大特征值→主成分方向", "动态系统：λmax 决定长期稳态", "图像压缩：丢弃小特征值方向"],
        selfCheck: ["为什么降维时保留最大特征值而不是最小特征值对应的方向？", "给你一个 2×2 协方差矩阵，解释如何做 PCA。"],
      },
    ],
  },
  {
    id: "applications",
    number: 8,
    title: "综合应用",
    description: "将前面学到的知识应用到实际项目中，包括图形变换、数据拟合、降维和工程案例。",
    prerequisites: ["所有前面的章节"],
    teachingPoints: [
      "线性代数的应用遍布计算机图形学、数据科学、工程",
      "综合运用之前学到的概念解决实际问题",
      "最小二乘拟合是线性方程组求解的自然延伸",
    ],
    commonMisconceptions: [
      "认为线性代数只是纯数学推导，没有实际用途",
      "认为最小二乘解必须完美拟合所有数据点",
    ],
    discussionQuestions: [
      "在日常生活中你还看到哪里用到了矩阵？",
      "为什么 3D 游戏在处理相机旋转时喜欢用四元数而不是矩阵？",
    ],
    knowledgePoints: [
      {
        id: "app-graphics",
        chapterId: "applications",
        title: "计算机图形变换",
        slug: "graphics-transform",
        objectives: ["用齐次坐标实现平移变换", "组合缩放、旋转和平移", "编写一个 2D 图形的完整变换"],
        motivation: "游戏里的人物移动、视野切换、3D 模型的变形——所有这些都是通过矩阵变换来实现的。学会这个，你就理解了一部分游戏引擎的工作原理。",
        intuition: "标准的 2×2 矩阵无法表示平移（因为它不能移动原点）。解决方案是引入'齐次坐标'——给二维点加一个额外的分量，用 3×3 矩阵来同时表示旋转、缩放和平移。",
        definition: "齐次坐标（homogeneous coordinates）在 (x,y) 基础上加一个 1（点在无穷远时加 0）。二维仿射变换可以写为 3×3 矩阵。平移矩阵 = [[1,0,tx], [0,1,ty], [0,0,1]]。旋转+平移的复合可以直接用 3×3 矩阵实现。",
        formulaLatex: "\\begin{pmatrix} x' \\\\ y' \\\\ 1 \\end{pmatrix} = \\begin{pmatrix} a & b & t_x \\\\ c & d & t_y \\\\ 0 & 0 & 1 \\end{pmatrix} \\begin{pmatrix} x \\\\ y \\\\ 1 \\end{pmatrix}",
        formulaExplanation: "前三列(a,b,c,d)是线性部分（旋转+缩放+剪切），最后一列(tx,ty)是平移部分。",
        example: {
          problem: "写出将点 (x,y) 先旋转 90° 再平移 (3,-1) 的齐次变换矩阵。",
          steps: [
            { description: "旋转部分", latex: "\\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix}" },
            { description: "齐次旋转矩阵 3×3", latex: "\\begin{pmatrix} 0 & -1 & 0 \\\\ 1 & 0 & 0 \\\\ 0 & 0 & 1 \\end{pmatrix}" },
            { description: "齐次平移矩阵", latex: "\\begin{pmatrix} 1 & 0 & 3 \\\\ 0 & 1 & -1 \\\\ 0 & 0 & 1 \\end{pmatrix}" },
            { description: "复合 = 平移×旋转", latex: "\\begin{pmatrix} 0 & -1 & 3 \\\\ 1 & 0 & -1 \\\\ 0 & 0 & 1 \\end{pmatrix}" },
          ],
          answer: "先旋转再平移的齐次矩阵",
          answerLatex: "\\begin{pmatrix} 0 & -1 & 3 \\\\ 1 & 0 & -1 \\\\ 0 & 0 & 1 \\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "忘记点坐标后面加 1", correction: "齐次坐标中，二维点表示为 (x, y, 1)，不是 (x, y)。" },
        ],
        summary: ["齐次坐标 = (x, y, 1)", "3×3 齐次矩阵 = 旋转/缩放 + 平移合一", "复合 = 从右到左乘"],
        selfCheck: ["如何表示一个先平移 (1,2) 再缩放 2 倍的齐次矩阵？", "3×3 齐次矩阵第三行一定是 [0 0 1] 吗？什么时候不是？"],
      },
      {
        id: "app-least-squares",
        chapterId: "applications",
        title: "最小二乘拟合",
        slug: "least-squares",
        objectives: ["理解 Ax=b 无解时的最佳近似解", "用正规方程 AᵀAx̂ = Aᵀb 求最小二乘解", "用矩阵计算拟合直线"],
        motivation: "实验数据带噪声，不可能所有点都恰好落在一条直线上。最小二乘找出'最靠近所有点'的那条线——误差的平方和最小。",
        intuition: "从几何看：b 不在 A 的列空间中（无解），我们找 A 的列空间中最接近 b 的点 p。这个点 p 的误差 e = b-p 垂直于列空间。解 AᵀAx̂ = Aᵀb 即为最佳近似。",
        definition: "对欠定方程 Ax=b̂ 的最小二乘解为 x̂ = (AᵀA)⁻¹Aᵀb。当 A 有满列秩时，(AᵀA)⁻¹ 存在。x̂ 使得 ||Ax-b|| 最小。",
        formulaLatex: "\\hat{x} = (A^T A)^{-1} A^T b",
        formulaExplanation: "AᵀA 是方阵（n×n），如果 A 列满秩则它是可逆的。这个解是从正规方程 AᵀAx = Aᵀb 导出的。",
        example: {
          problem: "数据点：(0,1), (1,3), (2,4)。用最小二乘拟合直线 y=ax+b。",
          steps: [
            { description: "设 Ax = b：三个方程、两个未知数", latex: "\\begin{pmatrix} 0 & 1 \\\\ 1 & 1 \\\\ 2 & 1 \\end{pmatrix} \\begin{pmatrix} a \\\\ b \\end{pmatrix} = \\begin{pmatrix} 1 \\\\ 3 \\\\ 4 \\end{pmatrix}" },
            { description: "AᵀA", latex: "A^TA = \\begin{pmatrix}5 & 3 \\\\ 3 & 3\\end{pmatrix}" },
            { description: "Aᵀb", latex: "A^Tb = \\begin{pmatrix}11 \\\\ 8\\end{pmatrix}" },
            { description: "解法方程", latex: "\\begin{pmatrix}a\\\\b\\end{pmatrix} = \\begin{pmatrix}1.5 \\\\ 1.17\\end{pmatrix}" },
            { description: "拟合直线", latex: "y = 1.5x + 1.17" },
          ],
          answer: "y = 1.5x + 1.17",
          answerLatex: "y = 1.5x + 1.17",
        },
        commonMistakes: [
          { mistake: "忘记 A 必须满列秩才能用 (AᵀA)⁻¹", correction: "如果 A 的列线性相关，(AᵀA) 不可逆，需要用伪逆或正则化方法。" },
        ],
        summary: ["最小二乘 → ||Ax-b|| 最小化", "正规方程：AᵀAx̂ = Aᵀb", "x̂ = (AᵀA)⁻¹Aᵀb"],
        selfCheck: ["为什么误差向量 e 必须垂直于 A 的列空间？", "数据点恰好落在一条直线上时，最小二乘解会是什么？"],
      },
      {
        id: "app-dim-reduction",
        chapterId: "applications",
        title: "简单的数据降维思想",
        slug: "dimension-reduction",
        objectives: ["理解为什么要降维（可视化、去噪、加速）", "理解 PCA 的基本流程", "手动实现一个简单的 2D→1D 投影"],
        motivation: "你的数据有100个维度，但人眼最多只能看3个维度。如何把100维数据'压缩'到2维，同时尽量不丢失信息？答案是 PCA（主成分分析）——找最大方差的方向做投影。",
        intuition: "数据就像一堆散在桌上的点。如果你在某个角度看它们（沿某个方向投影），点和点之间的区别可能被保留得很好（方差大）；换个角度看，所有点可能重叠在一起（方差小）。PCA 做的就是找到第一个角度（方差最大的方向）。",
        definition: "PCA 算法：(1) 数据中心化（减均值）；(2) 计算协方差矩阵 C；(3) 求 C 的特征值和特征向量（λ₁≥λ₂≥...）；(4) 选前 k 个特征向量对应的方向作为新坐标轴（主成分）；(5) 将数据投影到这些方向上。",
        formulaLatex: "C = \\frac{1}{n-1}(X - \\bar{X})^T(X - \\bar{X}), \\quad C\\vec{v} = \\lambda\\vec{v}",
        formulaExplanation: "C 的特征值衡量各方向上的方差大小。λ₁ 最大 = 主成分1（数据最发散的方向）。",
        example: {
          problem: "数据 (1,2), (3,4), (5,6) 需要降维到 1 维。简述前两步。",
          steps: [
            { description: "1. 中心化：减去均值 (3,4)", latex: "\\text{中心化后：}(-2,-2), (0,0), (2,2)" },
            { description: "2. 计算协方差矩阵", latex: "C = \\begin{pmatrix} 4 & 4 \\\\ 4 & 4 \\end{pmatrix}" },
            { description: "3. 特征值和特征向量", latex: "\\lambda_1=8, v_1=(1,1)/\\sqrt{2}; \\lambda_2=0" },
            { description: "4. 投影到 (1,1) 方向（保留100%方差）", latex: "\\text{投影到主成分上}" },
          ],
          answer: "沿 (1,1) 方向做一维投影",
          answerLatex: "\\text{主成分方向}=(1,1)/\\sqrt{2}",
        },
        commonMistakes: [
          { mistake: "忘记减均值就直接算协方差", correction: "必须先中心化数据（减均值），否则协方差矩阵包含了位置偏移。" },
        ],
        summary: ["降维 = 保留最大方差方向", "PCA: 协方差特征分解 → 选前k特征向量 → 投影", "特征值大小 = 保留的信息量"],
        selfCheck: ["解释为什么在 PCA 中用协方差矩阵而不是原始数据矩阵。", "如果前两个特征值的和等于总方差的95%，说明什么？"],
      },
      {
        id: "app-case-studies",
        chapterId: "applications",
        title: "网络、工程或物理中的实际案例",
        slug: "case-studies",
        objectives: ["用矩阵表示图（网络）中的连接关系", "用特征值分析网络的重要节点", "用线性系统求解电路和力学问题"],
        motivation: "互联网：网页和网页之间的链接 → 矩阵（邻接矩阵）。PageRank 通过求最大特征值来找出最重要的网页。工程中的桁架受力分析、电路中的网孔电流法——都可以用矩阵简洁表达。",
        intuition: "图的邻接矩阵：第 i 行第 j 列为 1 表示节点 i 连接到节点 j。邻接矩阵的幂 A² 的元素告诉你'走两步的路径'数量。PageRank 的核心是找到这个矩阵的主特征向量。",
        definition: "图 G 有 n 个顶点，邻接矩阵 A[n×n] 中 aᵢⱼ=1 如果顶点 i 和 j 有边相连（否则为 0）。Aᵏ 的 (i,j) 元素 = 从 i 到 j 恰好 k 步的路径条数。PageRank = 归一化后邻接矩阵的主特征向量。",
        formulaLatex: "A_{ij} = \\begin{cases} 1, & \\text{若 i 和 j 有边相连} \\\\ 0, & \\text{否则} \\end{cases}",
        formulaExplanation: "邻接矩阵存储图的连接关系。PageRank 解向量 r 满足 r = αPr + (1-α)v（其中 P 是转移矩阵）。",
        example: {
          problem: "三个网页：A链到B和C，B链到C，C链到A。写出邻接矩阵。",
          steps: [
            { description: "A→B, A→C; B→C; C→A", latex: "" },
            { description: "邻接矩阵（行=源，列=目标）", latex: "\\begin{pmatrix} 0 & 1 & 1 \\\\ 0 & 0 & 1 \\\\ 1 & 0 & 0 \\end{pmatrix}" },
          ],
          answer: "3×3 邻接矩阵",
          answerLatex: "\\begin{pmatrix} 0 & 1 & 1 \\\\ 0 & 0 & 1 \\\\ 1 & 0 & 0 \\end{pmatrix}",
        },
        commonMistakes: [
          { mistake: "混淆邻接矩阵的行列方向（源→目标 vs 目标→源）", correction: "约定：如果边从 i 指向 j，aᵢⱼ=1。即行 = 来源，列 = 目标。" },
        ],
        summary: ["图 = 网络（节点+边）", "邻接矩阵 = 图的矩阵表示", "特征向量分解 = 找出网络中的重要节点"],
        selfCheck: ["A² 的元素代表什么？", "为什么 PageRank 只需要主特征向量？"],
      },
    ],
  },
];

export const COURSE_CHAPTERS = CHAPTERS;
export const CHAPTER_LIST = CHAPTERS.map((ch) => ({
  id: ch.id,
  number: ch.number,
  title: ch.title,
  description: ch.description,
  prerequisites: ch.prerequisites,
}));
